### ISSUE TITLE
Web interface work, API not

### ISSUE THREAD

**Issue by lyfar** [harry0703/MoneyPrinterTurbo#10]
Hi, web interface works fine, but when I try to run test API call from swagger http://localhost:8080/docs#/V1/create_video_api_v1_videos_post

I receive this response:

## generating audio
2024-03-15 17:01:23 | INFO | "./app/services/voice.py:11": tts - start, voice name: zh-CN-XiaoxiaoNeural
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/miniconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 412, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/miniconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/opt/miniconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/miniconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/miniconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/opt/miniconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/opt/miniconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/miniconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/miniconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/miniconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/miniconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/opt/miniconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/opt/miniconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/opt/miniconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/miniconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/miniconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
  File "/opt/miniconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/opt/miniconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/ivanivanov/MoneyPrinterTurbo/app/controllers/v1/video.py", line 29, in create_video
    result = tm.start(task_id=task_id, params=body)
  File "/Users/ivanivanov/MoneyPrinterTurbo/app/services/task.py", line 63, in start
    sub_maker = voice.tts(text=script, voice_name=voice_name, voice_file=audio_file)
  File "/Users/ivanivanov/MoneyPrinterTurbo/app/services/voice.py", line 24, in tts
    sub_maker = asyncio.run(_do())
  File "/opt/miniconda3/envs/MoneyPrinterTurbo/lib/python3.10/asyncio/runners.py", line 33, in run
    raise RuntimeError(
RuntimeError: asyncio.run() cannot be called from a running event loop
/opt/miniconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py:-1: RuntimeWarning: coroutine 'tts.<locals>._do' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**Comment by harry0703** [comment]
@lyfar I attempted to fix the issue, please update the code and try again.
