### ISSUE TITLE
语音生成mp3格式会被损坏

### ISSUE THREAD

**Issue by yuanshuo1022** [harry0703/MoneyPrinterTurbo#122]
报错：## generating subtitle, provider: edge
2024-03-30 20:50:21 | WARNING | "./app\services\voice.py:1089": create_subtitle - failed, sub_items len: 0, script_lines len: 49
2024-03-30 20:50:21 | WARNING | "./app\services\task.py:87": start - subtitle file not found, fallback to whisper
2024-03-30 20:50:21 | INFO | "./app\services\subtitle.py:25": create - start, output file: .\storage\tasks\f93a4686-28a2-4842-95b5-16dc13e9d8b4\subtitle.srt
Format mp3 detected only with low score of 1, misdetection possible!
Failed to read frame size: Could not seek to 1026.
2024-03-30 20:50:21.594 Uncaught app exception
Traceback (most recent call last):
  File "E:\AIstudy\conda\envs\MoneyPrinterTurbo\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
  File "E:\AIstudy\code\MoneyPrinterTurbo\webui\Main.py", line 376, in <module>
    tm.start(task_id=task_id, params=params)
  File "E:\AIstudy\code\MoneyPrinterTurbo\app\services\task.py", line 95, in start
    subtitle.create(audio_file=audio_file, subtitle_file=subtitle_path)
  File "E:\AIstudy\code\MoneyPrinterTurbo\app\services\subtitle.py", line 29, in create
    segments, info = model.transcribe(
  File "E:\AIstudy\conda\envs\MoneyPrinterTurbo\lib\site-packages\faster_whisper\transcribe.py", line 294, in transcribe
    audio = decode_audio(audio, sampling_rate=sampling_rate)
  File "E:\AIstudy\conda\envs\MoneyPrinterTurbo\lib\site-packages\faster_whisper\audio.py", line 46, in decode_audio
    with av.open(input_file, mode="r", metadata_errors="ignore") as container:
  File "av\\container\\core.pyx", line 401, in av.container.core.open
  File "av\\container\\core.pyx", line 265, in av.container.core.Container.__cinit__
  File "av\\container\\core.pyx", line 285, in av.container.core.Container.err_check
  File "av\\error.pyx", line 336, in av.error.err_check
av.error.ValueError: [Errno 22] Invalid argument: 'E:\\AIstudy\\code\\MoneyPrinterTurbo\\storage\\tasks\\f93a4686-28a2-4842-95b5-16dc13e9d8b4\\audio.mp3'; last error log: [mp3] Failed to read frame size: Could not seek to 1026.
![Snipaste_2024-03-30_20-57-38](https://github.com/harry0703/MoneyPrinterTurbo/assets/84314633/409291c2-edac-4454-9a6d-21f77c9e4c62)

**Comment by balless** [comment]
我错误给你一样

**Comment by MoXiaoluo** [comment]
同样的问题。

**Comment by harry0703** [comment]
音频文件应该是生成失败了，看看是否有错误日志？
音频生成服务，需要访问网络，有时候需要VPN才能访问
确保网络通畅，再试试看

**Comment by yuanshuo1022** [comment]
> 音频文件应该是生成失败了，看看是否有错误日志？ 音频生成服务，需要访问网络，有时候需要VPN才能访问 确保网络通畅，再试试看
logs文件夹下的日志是空白的，当我使用vpn的时候ping油管的视频能ping通，但是依旧报错，似乎是url无法正确的被处理
![ping](https://github.com/harry0703/MoneyPrinterTurbo/assets/84314633/3e475116-edeb-4658-a09c-e9826039c1ac)

![报错](https://github.com/harry0703/MoneyPrinterTurbo/assets/84314633/6ae5a4e2-491f-439f-954c-2ae3aaf9cbe7)

**Comment by harry0703** [comment]
看起来确实是网络问题，建议你使用VPN的全局流量模式

**Comment by zhaozhiming** [comment]
我用VPN也是报这个错误，可以调openai接口生成文案，说明VPN是没问题的

```bash
## generating subtitle, provider: edge
2024-04-02 13:49:29 | WARNING | "./app/services/voice.py:1089": create_subtitle - failed, sub_items len: 0, script_lines len: 11
2024-04-02 13:49:29 | WARNING | "./app/services/task.py:98": start - subtitle file not found, fallback to whisper
2024-04-02 13:49:29 | INFO | "./app/services/subtitle.py:20": create - loading model: large-v3, device: CPU, compute_type: int8
2024-04-02 13:49:34 | INFO | "./app/services/subtitle.py:25": create - start, output file: ./storage/tasks/18921788-bb9d-402a-84f3-42f388caa0a6/subtitle.srt
Format mp3 detected only with low score of 1, misdetection possible!
Failed to read frame size: Could not seek to 1026.
2024-04-02 13:49:34.587 Uncaught app exception
Traceback (most recent call last):
  File "miniconda3/envs/video/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
  File "MoneyPrinterTurbo/webui/Main.py", line 376, in <module>
    tm.start(task_id=task_id, params=params)
  File "MoneyPrinterTurbo/app/services/task.py", line 106, in start
    subtitle.create(audio_file=audio_file, subtitle_file=subtitle_path)
  File "MoneyPrinterTurbo/app/services/subtitle.py", line 29, in create
    segments, info = model.transcribe(
                     ^^^^^^^^^^^^^^^^^
  File "miniconda3/envs/video/lib/python3.11/site-packages/faster_whisper/transcribe.py", line 294, in transcribe
    audio = decode_audio(audio, sampling_rate=sampling_rate)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "miniconda3/envs/video/lib/python3.11/site-packages/faster_whisper/audio.py", line 46, in decode_audio
    with av.open(input_file, mode="r", metadata_errors="ignore") as container:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "av/container/core.pyx", line 401, in av.container.core.open
  File "av/container/core.pyx", line 265, in av.container.core.Container.__cinit__
  File "av/container/core.pyx", line 285, in av.container.core.Container.err_check
  File "av/error.pyx", line 336, in av.error.err_check
av.error.ValueError: [Errno 22] Invalid argument: 'MoneyPrinterTurbo/storage/tasks/18921788-bb9d-402a-84f3-42f388caa0a6/audio.mp3'; last error log: [mp3] Failed to read frame size: Could not seek to 1026.
```

**Comment by a231279478** [comment]
我也遇到同样的问题，VPN也是使用的全局流量模式。

**Comment by Deali-Axy** [comment]
我也遇到这个问题

**Comment by kamalkk** [comment]
遇到相同的问题，这块有解决的，mp3 file size 0

**Comment by Ninsh92** [comment]
把朗读声音的配音选择汉语选项，默认的不是汉语的，配音也生成不了汉语，所以会报错

**Comment by Ninsh92** [comment]
> > 音频文件应该是生成失败了，看看是否有错误日志？ 音频生成服务，需要访问网络，有时候需要VPN才能访问确保网络通畅，再试试看
> > logs文件夹下的是空白的，当我使用vpn时的时候ping油管的域名能ping通，但是仍然报错，似乎是url无法正确的被处理
> > ![平](https://private-user-images.githubusercontent.com/84314633/318396518-13f3b836-d94e-4365-b037-246cd7cb337c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNjM2ODcsIm5iZiI6MTcxMjE2MzM4NywicGF0aCI6Ii84NDMxNDYzMy8zMTgzOTY1MTgtMTNmM2I4MzYtZDk0ZS00MzY1LWIwMzctMjQ2Y2Q3Y2IzMzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDE2NTYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4OGY1OGM1MzQxZWExZWEwZTA5M2RmOWY3OGMxYjA0OWE2OTE2MmNlNjk4Zjk1OWE1ZWZkYTIyNzllMzBlYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TuhnbEfMbArdDEYtih-6_E1P-oc3atcp55ZYpp5FyhI)
> 
> ![报错](https://private-user-images.githubusercontent.com/84314633/318395853-6ae5a4e2-491f-439f-954c-2ae3aaf9cbe7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNjM2ODcsIm5iZiI6MTcxMjE2MzM4NywicGF0aCI6Ii84NDMxNDYzMy8zMTgzOTU4NTMtNmFlNWE0ZTItNDkxZi00MzlmLTk1NGMtMmFlM2FhZjljYmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDE2NTYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmYzU0YmY5OTgxYTg1NTExOTA4MDUxZjgxN2U2Y2ViM2FjNzkwMzlhYzQzMmU3Y2U3ZmQzY2I3NDFlN2U0NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pCm3rCRrYCcM-OJpvmdePg7p1Ed975sgq0L36rHn5bU)

把朗读声音的配音选择汉语选项，默认的不是汉语的，配音也生成不了汉语，所以会报错

**Comment by yuanshuo1022** [comment]
> > > 音频文件应该是生成失败了，看看是否有错误日志？ 音频生成服务，需要访问网络，有时候需要VPN才能访问确保网络通畅，再试试看
> > > logs文件夹下的是空白的，当我使用vpn时的时候ping油管的域名能ping通，但是仍然报错，似乎是url无法正确的被处理
> > > ![平](https://private-user-images.githubusercontent.com/84314633/318396518-13f3b836-d94e-4365-b037-246cd7cb337c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNjM2ODcsIm5iZiI6MTcxMjE2MzM4NywicGF0aCI6Ii84NDMxNDYzMy8zMTgzOTY1MTgtMTNmM2I4MzYtZDk0ZS00MzY1LWIwMzctMjQ2Y2Q3Y2IzMzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDE2NTYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4OGY1OGM1MzQxZWExZWEwZTA5M2RmOWY3OGMxYjA0OWE2OTE2MmNlNjk4Zjk1OWE1ZWZkYTIyNzllMzBlYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TuhnbEfMbArdDEYtih-6_E1P-oc3atcp55ZYpp5FyhI)
> > 
> > 
> > ![报错](https://private-user-images.githubusercontent.com/84314633/318395853-6ae5a4e2-491f-439f-954c-2ae3aaf9cbe7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNjM2ODcsIm5iZiI6MTcxMjE2MzM4NywicGF0aCI6Ii84NDMxNDYzMy8zMTgzOTU4NTMtNmFlNWE0ZTItNDkxZi00MzlmLTk1NGMtMmFlM2FhZjljYmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDE2NTYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmYzU0YmY5OTgxYTg1NTExOTA4MDUxZjgxN2U2Y2ViM2FjNzkwMzlhYzQzMmU3Y2U3ZmQzY2I3NDFlN2U0NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pCm3rCRrYCcM-OJpvmdePg7p1Ed975sgq0L36rHn5bU)
> 
> 把朗读声音的配音选择汉语选项，默认的不是汉语的，配音也生成不了汉语，所以会报错

我尝试了一下，问题解决了，感谢
