### ISSUE TITLE
gpu加载报错

### ISSUE THREAD

**Issue by emVisible** [harry0703/MoneyPrinterTurbo#126]
Format mp3 detected only with low score of 1, misdetection possible!
Failed to read frame size: Could not seek to 1026.

2024-03-31 12:16:30.234 Uncaught app exception
Traceback (most recent call last):
  File "C:\_code\env\env_python\miniconda\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
  File "C:\_code\_project\MoneyPrinterTurbo\webui\Main.py", line 376, in <module>
    tm.start(task_id=task_id, params=params)
  File "C:\_code\_project\MoneyPrinterTurbo\app\services\task.py", line 95, in start
    subtitle.create(audio_file=audio_file, subtitle_file=subtitle_path)
  File "C:\_code\_project\MoneyPrinterTurbo\app\services\subtitle.py", line 29, in create
    segments, info = model.transcribe(
                     ^^^^^^^^^^^^^^^^^
  File "C:\_code\env\env_python\miniconda\Lib\site-packages\faster_whisper\transcribe.py", line 294, in transcribe
    audio = decode_audio(audio, sampling_rate=sampling_rate)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_code\env\env_python\miniconda\Lib\site-packages\faster_whisper\audio.py", line 46, in decode_audio
    with av.open(input_file, mode="r", metadata_errors="ignore") as container:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "av\\container\\core.pyx", line 401, in av.container.core.open
  File "av\\container\\core.pyx", line 265, in av.container.core.Container.__cinit__
  File "av\\container\\core.pyx", line 285, in av.container.core.Container.err_check
  File "av\\error.pyx", line 336, in av.error.err_check
av.error.ValueError: [Errno 22] Invalid argument: 'C:\\_code\\_project\\MoneyPrinterTurbo\\storage\\tasks\\d3f80c57-eb3a-48bf-8178-334fbc91373c\\audio.mp3'; last error log: [mp3] Failed to read frame size: Could not seek to 1026.

**Comment by harry0703** [comment]
看看任务输出目录下的 audio.mp3 文件是否生成成功了？
音频生成可能需要VPN网络
