### ISSUE TITLE
win11运行webui.bat报错

### ISSUE THREAD

**Issue by zhang-jianqiang** [harry0703/MoneyPrinterTurbo#130]
环境安装完成，执行webui.bat时报以下错误：
2024-03-31 15:55:24.342 | INFO     | app.config.config:<module>:15 - load config from file: D:\pythoncdoe\MoneyPrinterTurbo/config.toml
2024-03-31 15:55:25.378 Uncaught app exception
Traceback (most recent call last):
  File "D:\software\python\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
  File "D:\pythoncdoe\MoneyPrinterTurbo\webui\Main.py", line 25, in <module>
    from app.services import task as tm, llm, voice
  File "D:\pythoncdoe\MoneyPrinterTurbo\app\services\task.py", line 10, in <module>
    from app.services import llm, material, voice, video, subtitle
  File "D:\pythoncdoe\MoneyPrinterTurbo\app\services\subtitle.py", line 4, in <module>
    from faster_whisper import WhisperModel
  File "D:\software\python\lib\site-packages\faster_whisper\__init__.py", line 2, in <module>
    from faster_whisper.transcribe import WhisperModel
  File "D:\software\python\lib\site-packages\faster_whisper\transcribe.py", line 10, in <module>
    import ctranslate2
  File "D:\software\python\lib\site-packages\ctranslate2\__init__.py", line 18, in <module>
    ctypes.CDLL(library)
  File "D:\software\python\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\software\python\lib\site-packages\ctranslate2\ctranslate2.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by harry0703** [comment]
看起来像是依赖库没有安装完整（也许安装的过程中出错了）
先执行 `pip install -r requirements.txt` 安装依赖
安装的时候，看看是否有错误发生

**Comment by 41232** [comment]
在M1 Mac也有同樣問題。執行sh webui.sh報錯。檢查過所有dependencies 都已安裝完成：
TOMLDecodeError: Unclosed array (at line 7, column 25)
Traceback:
File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
File "/Users/xxx/PycharmProjects/MoneyPrinterTurbo/webui/Main.py", line 25, in <module>
    from app.services import task as tm, llm, voice
File "/Users/xxx/PycharmProjects/MoneyPrinterTurbo/app/services/task.py", line 8, in <module>
    from app.config import config
File "/Users/xxx/PycharmProjects/MoneyPrinterTurbo/app/config/__init__.py", line 6, in <module>
    from app.config import config
File "/Users/xxx/PycharmProjects/MoneyPrinterTurbo/app/config/config.py", line 18, in <module>
    _cfg = tomli.load(fp)
File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/tomli/_parser.py", line 66, in load
    return loads(s, parse_float=parse_float)
File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/tomli/_parser.py", line 102, in loads
    pos = key_value_rule(src, pos, out, header, parse_float)
File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/tomli/_parser.py", line 326, in key_value_rule
    pos, key, value = parse_key_value_pair(src, pos, parse_float)
File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/tomli/_parser.py", line 369, in parse_key_value_pair
    pos, value = parse_value(src, pos, parse_float)
File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/tomli/_parser.py", line 616, in parse_value
    return parse_array(src, pos, parse_float)
File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/tomli/_parser.py", line 428, in parse_array
    raise suffixed_err(src, pos, "Unclosed array")

**Comment by harry0703** [comment]
这个是配置文件中的格式写错了，大概率是pelexs的API key

在 2024年3月31日，18:39，41232 ***@***.***> 写道：

﻿

在M1 Mac也有同樣問題。執行sh webui.sh報錯。檢查過所有dependencies 都已安裝完成：
TOMLDecodeError: Unclosed array (at line 7, column 25)
Traceback:
File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 542, in _run_script
exec(code, module.dict)
File "/Users/xxx/PycharmProjects/MoneyPrinterTurbo/webui/Main.py", line 25, in
from app.services import task as tm, llm, voice
File "/Users/xxx/PycharmProjects/MoneyPrinterTurbo/app/services/task.py", line 8, in
from app.config import config
File "/Users/xxx/PycharmProjects/MoneyPrinterTurbo/app/config/init.py", line 6, in
from app.config import config
File "/Users/xxx/PycharmProjects/MoneyPrinterTurbo/app/config/config.py", line 18, in
_cfg = tomli.load(fp)
File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/tomli/_parser.py", line 66, in load
return loads(s, parse_float=parse_float)
File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/tomli/_parser.py", line 102, in loads
pos = key_value_rule(src, pos, out, header, parse_float)
File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/tomli/_parser.py", line 326, in key_value_rule
pos, key, value = parse_key_value_pair(src, pos, parse_float)
File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/tomli/_parser.py", line 369, in parse_key_value_pair
pos, value = parse_value(src, pos, parse_float)
File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/tomli/_parser.py", line 616, in parse_value
return parse_array(src, pos, parse_float)
File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/tomli/_parser.py", line 428, in parse_array
raise suffixed_err(src, pos, "Unclosed array")

**Comment by ZhouChaunge** [comment]
是的，非常感谢您的项目，我已经成功复现。
感谢您的开源精神，我已经在git上面star，很有潜力的项目
---- 回复的原邮件 ----
***@***.***>发送日期2024年3月31日 ***@***.***>***@***.***>主题Re: [harry0703/MoneyPrinterTurbo] win11运行webui.bat报错 (Issue #130)
在M1 Mac也有同樣問題。執行sh webui.sh報錯。檢查過所有dependencies 都已安裝完成：
TOMLDecodeError: Unclosed array (at line 7, column 25)
Traceback:
File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 542, in _run_script
exec(code, module.dict)
File "/Users/xxx/PycharmProjects/MoneyPrinterTurbo/webui/Main.py", line 25, in 
from app.services import task as tm, llm, voice
File "/Users/xxx/PycharmProjects/MoneyPrinterTurbo/app/services/task.py", line 8, in 
from app.config import config
File "/Users/xxx/PycharmProjects/MoneyPrinterTurbo/app/config/init.py", line 6, in 
from app.config import config
File "/Users/xxx/PycharmProjects/MoneyPrinterTurbo/app/config/config.py", line 18, in 
_cfg = tomli.load(fp)
File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/tomli/_parser.py", line 66, in load
return loads(s, parse_float=parse_float)
File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/tomli/_parser.py", line 102, in loads
pos = key_value_rule(src, pos, out, header, parse_float)
File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/tomli/_parser.py", line 326, in key_value_rule
pos, key, value = parse_key_value_pair(src, pos, parse_float)
File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/tomli/_parser.py", line 369, in parse_key_value_pair
pos, value = parse_value(src, pos, parse_float)
File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/tomli/_parser.py", line 616, in parse_value
return parse_array(src, pos, parse_float)
File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/tomli/_parser.py", line 428, in parse_array
raise suffixed_err(src, pos, "Unclosed array")

**Comment by zhang-jianqiang** [comment]
> 看起来像是依赖库没有安装完整（也许安装的过程中出错了） 先执行 `pip install -r requirements.txt` 安装依赖 安装的时候，看看是否有错误发生

 DEPRECATION: moviepy is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for moviepy: started
  Running setup.py install for moviepy: finished with status 'done'
最后有一个这个报错，按照上面说的pip install 时加上 --use-pep517 参数可以了

**Comment by babyfengfjx** [comment]
好像在新版本上还是有这个问题啊
