### ISSUE TITLE
启动报错:'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by githuyong** [harry0703/MoneyPrinterTurbo#139]
windows下，运行 condaactivate MoneyPrinterTurbo这一步报错
`$ conda activate MoneyPrinterTurbo
Exception in thread Thread-5 (_readerthread):
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\miniconda3\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\miniconda3\Lib\subprocess.py", line 1597, in _readerthread
    buffer.append(fh.read())
                  ^^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 538: illegal multibyte sequence
ERROR conda.activate:native_path_to_unix(882): Unexpected cygpath error ('NoneType' object has no attribute 'strip')`

**Comment by harry0703** [comment]
可以看下这个帖子：
https://github.com/conda/conda/issues/3788
