### ISSUE TITLE
subtitle错误

### ISSUE THREAD

**Issue by czqasngit** [harry0703/MoneyPrinterTurbo#14]
2024-03-16 15:20:40.239 Uncaught app exception
Traceback (most recent call last):
  File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
  File "/Volumes/Work/GitHub/MoneyPrinterTurbo/webui/Main.py", line 153, in <module>
    tm.start(task_id=task_id, params=cfg)
  File "/Volumes/Work/GitHub/MoneyPrinterTurbo/app/services/task.py", line 93, in start
    video.generate_video(video_path=combined_video_path,
  File "/Volumes/Work/GitHub/MoneyPrinterTurbo/app/services/video.py", line 186, in generate_video
    subtitles = SubtitlesClip(subtitle_path, generator)
  File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/video/tools/subtitles.py", line 55, in __init__
    self.duration = max([tb for ((ta,tb), txt) in self.subtitles])
ValueError: max() arg is an empty sequence

**Comment by harry0703** [comment]
1. 检查下输出目录里面，是否有对应的srt文件，用vscode打开看看里面内容是否完整
2. 如果srt字幕文件有问题的话，可以重试下
3. 如果一直不行，可以把 subtitle_provider 换成whisper试试看
