### ISSUE TITLE
Uncaught app exception Traceback

### ISSUE THREAD

**Issue by pupheng** [harry0703/MoneyPrinterTurbo#143]
2024-04-01 22:40:14 | INFO | "./app\services\video.py:179": generate_video - using font: C:/Users/hourp/Downloads/MoneyPrinterTurbo-V1/resource/fonts/STHeitiLight.ttc
2024-04-01 22:40:14.482 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\hourp\anaconda3\envs\MoneyPrinterTurbo\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\hourp\Downloads\MoneyPrinterTurbo-V1\webui\Main.py", line 376, in <module>
    tm.start(task_id=task_id, params=params)
  File "C:\Users\hourp\Downloads\MoneyPrinterTurbo-V1\app\services\task.py", line 158, in start
    video.generate_video(video_path=combined_video_path,
  File "C:\Users\hourp\Downloads\MoneyPrinterTurbo-V1\app\services\video.py", line 214, in generate_video
    sub = SubtitlesClip(subtitles=subtitle_path, make_textclip=generator, encoding='utf-8')
  File "C:\Users\hourp\anaconda3\envs\MoneyPrinterTurbo\lib\site-packages\moviepy\video\tools\subtitles.py", line 69, in __init__
    self.duration = max([tb for ((ta, tb), txt) in self.subtitles])
  File "C:\Users\hourp\anaconda3\envs\MoneyPrinterTurbo\lib\site-packages\moviepy\video\tools\subtitles.py", line 69, in <listcomp>
    self.duration = max([tb for ((ta, tb), txt) in self.subtitles])
TypeError: cannot unpack non-iterable NoneType object

**Comment by harry0703** [comment]
Thank you for your feedback. 
Could you please package and upload the `subtitle.srt` and `audio.mp3` files from the task output directory here? 
This will help me locate and resolve the issue. 
Thank you.
