### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'C:\\AI\\MoneyPrinterTurbo\\storage\\logs\\server.log'

### ISSUE THREAD

**Issue by Dalongwang2025** [harry0703/MoneyPrinterTurbo#175]
(MoneyPrinterTurbo) C:\AI\MoneyPrinterTurbo>webui.bat
***** Current directory: C:\AI\MoneyPrinterTurbo *****

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.1.9:8501

2024-04-05 20:08:42.855 | INFO     | app.config.config:<module>:16 - load config from file: C:\AI\MoneyPrinterTurbo/config.toml
2024-04-05 20:08:42.886 Uncaught app exception
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\MoneyPrinterTurbo\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
  File "C:\AI\MoneyPrinterTurbo\webui\Main.py", line 25, in <module>
    from app.services import task as tm, llm, voice
  File "C:\AI\MoneyPrinterTurbo\app\services\task.py", line 8, in <module>
    from app.config import config
  File "C:\AI\MoneyPrinterTurbo\app\config\__init__.py", line 51, in <module>
    __init_logger()
  File "C:\AI\MoneyPrinterTurbo\app\config\__init__.py", line 39, in __init_logger
    logger.add(
  File "C:\ProgramData\Anaconda3\envs\MoneyPrinterTurbo\lib\site-packages\loguru\_logger.py", line 795, in add
    wrapped_sink = FileSink(path, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\MoneyPrinterTurbo\lib\site-packages\loguru\_file_sink.py", line 192, in __init__
    self._create_file(path)
  File "C:\ProgramData\Anaconda3\envs\MoneyPrinterTurbo\lib\site-packages\loguru\_file_sink.py", line 226, in _create_file
    self._file = open(path, **self._kwargs)
PermissionError: [Errno 13] Permission denied: 'C:\\AI\\MoneyPrinterTurbo\\storage\\logs\\server.log'
2024-04-05 20:08:50.931 Uncaught app exception
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\MoneyPrinterTurbo\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
  File "C:\AI\MoneyPrinterTurbo\webui\Main.py", line 25, in <module>
    from app.services import task as tm, llm, voice
  File "C:\AI\MoneyPrinterTurbo\app\services\task.py", line 8, in <module>
    from app.config import config
  File "C:\AI\MoneyPrinterTurbo\app\config\__init__.py", line 51, in <module>
    __init_logger()
  File "C:\AI\MoneyPrinterTurbo\app\config\__init__.py", line 39, in __init_logger
    logger.add(
  File "C:\ProgramData\Anaconda3\envs\MoneyPrinterTurbo\lib\site-packages\loguru\_logger.py", line 795, in add
    wrapped_sink = FileSink(path, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\MoneyPrinterTurbo\lib\site-packages\loguru\_file_sink.py", line 192, in __init__
    self._create_file(path)
  File "C:\ProgramData\Anaconda3\envs\MoneyPrinterTurbo\lib\site-packages\loguru\_file_sink.py", line 226, in _create_file
    self._file = open(path, **self._kwargs)
PermissionError: [Errno 13] Permission denied: 'C:\\AI\\MoneyPrinterTurbo\\storage\\logs\\server.log'

**Comment by Dalongwang2025** [comment]
这个问题咋解决啊？按照copilot的方法都试了，还是不行。
![屏幕截图 2024-04-05 201356](https://github.com/harry0703/MoneyPrinterTurbo/assets/43041395/937503a9-044d-415f-8872-9de31d0fa9d4)
遇到PermissionError: [Errno 13] Permission denied错误通常意味着程序没有足够的权限来写入或访问指定的文件。在这种情况下，错误是由于尝试写入server.log日志文件时被拒绝。以下是解决这个问题的步骤：

以管理员身份运行：关闭当前的命令提示符窗口，然后重新以管理员身份打开。在Windows上，可以通过在开始菜单中找到命令提示符，右键点击它，然后选择“以管理员身份运行”。
检查日志文件夹的权限：使用文件资源管理器导航到C:\AI\MoneyPrinterTurbo\storage\logs\，右键点击logs文件夹，选择“属性”，然后切换到“安全”选项卡。在这里，确保你的用户账户有权限写入文件。
确保日志文件没有被其他程序使用：有时候，如果日志文件已经被另一个进程打开，可能会导致权限错误。你可以尝试重启计算机来关闭所有可能使用该文件的程序。
检查文件路径：确认server.log文件的路径是正确的，并且该路径对应的文件夹存在且可写。
如果问题仍然存在，你可能需要检查你的程序配置或联系程序的开发者获取更多帮助。希望这些步骤能帮助你解决问题！如果还有其他疑问，欢迎继续提问。🛠️

**Comment by harry0703** [comment]
正在看这个问题，稍等哈~

**Comment by harry0703** [comment]
更新代码再试试，应该是修复了，感谢反馈
