### ISSUE TITLE
ModuleNotFoundError: No module named 'google.generativeai'

### ISSUE THREAD

**Issue by gh2571527745** [harry0703/MoneyPrinterTurbo#181]
2024-04-07 11:14:48.660 | INFO     | app.config.config:<module>:16 - load config from file: D:\soft\MoneyPrinter\MoneyPrinterTurbo/config.toml
2024-04-07 11:14:49.514 Uncaught app exception
Traceback (most recent call last):
  File "D:\soft\conda\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
  File "D:\soft\MoneyPrinter\MoneyPrinterTurbo\webui\Main.py", line 25, in <module>
    from app.services import task as tm, llm, voice
  File "D:\soft\MoneyPrinter\MoneyPrinterTurbo\app\services\task.py", line 11, in <module>
    from app.services import llm, material, voice, video, subtitle
  File "D:\soft\MoneyPrinter\MoneyPrinterTurbo\app\services\llm.py", line 8, in <module>
    import google.generativeai as genai
ModuleNotFoundError: No module named 'google.generativeai'

**Comment by gh2571527745** [comment]
运行时，报了个这个错误

**Comment by harry0703** [comment]
安装依赖
```
pip install -r requirements.txt
```
