### ISSUE TITLE
生成视频时报错`TypeError: sequence item 2: expected str instance, NoneType found`

### ISSUE THREAD

**Issue by KevinZhang19870314** [harry0703/MoneyPrinterTurbo#193]
```
## generating video: 1 => D:\kevinzhang\tmp\MoneyPrinterTurbo\storage\tasks\c8448f7a-991d-465e-a1c3-d4203ce2380a\final-1.mp4
2024-04-08 15:54:46 | INFO | "./app\services\video.py:176": generate_video - start, video size: 1080 x 1920
2024-04-08 15:54:46 | INFO | "./app\services\video.py:177": generate_video -   ① video: D:\kevinzhang\tmp\MoneyPrinterTurbo\storage\tasks\c8448f7a-991d-465e-a1c3-d4203ce2380a\combined-1.mp4
2024-04-08 15:54:46 | INFO | "./app\services\video.py:178": generate_video -   ② audio: D:\kevinzhang\tmp\MoneyPrinterTurbo\storage\tasks\c8448f7a-991d-465e-a1c3-d4203ce2380a\audio.mp3
2024-04-08 15:54:46 | INFO | "./app\services\video.py:179": generate_video -   ③ subtitle: D:\kevinzhang\tmp\MoneyPrinterTurbo\storage\tasks\c8448f7a-991d-465e-a1c3-d4203ce2380a\subtitle.srt
2024-04-08 15:54:46 | INFO | "./app\services\video.py:180": generate_video -   ④ output: D:\kevinzhang\tmp\MoneyPrinterTurbo\storage\tasks\c8448f7a-991d-465e-a1c3-d4203ce2380a\final-1.mp4
2024-04-08 15:54:46 | INFO | "./app\services\video.py:190": generate_video - using font: D:/kevinzhang/tmp/MoneyPrinterTurbo/resource/fonts/STHeitiLight.ttc
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\kevinzhang\tmp\MoneyPrinterTurbo\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 412, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\kevinzhang\tmp\MoneyPrinterTurbo\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "D:\kevinzhang\tmp\MoneyPrinterTurbo\venv\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\kevinzhang\tmp\MoneyPrinterTurbo\venv\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\kevinzhang\tmp\MoneyPrinterTurbo\venv\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "D:\kevinzhang\tmp\MoneyPrinterTurbo\venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "D:\kevinzhang\tmp\MoneyPrinterTurbo\venv\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\kevinzhang\tmp\MoneyPrinterTurbo\venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "D:\kevinzhang\tmp\MoneyPrinterTurbo\venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "D:\kevinzhang\tmp\MoneyPrinterTurbo\venv\lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\kevinzhang\tmp\MoneyPrinterTurbo\venv\lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "D:\kevinzhang\tmp\MoneyPrinterTurbo\venv\lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "D:\kevinzhang\tmp\MoneyPrinterTurbo\venv\lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\kevinzhang\tmp\MoneyPrinterTurbo\venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "D:\kevinzhang\tmp\MoneyPrinterTurbo\venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "D:\kevinzhang\tmp\MoneyPrinterTurbo\venv\lib\site-packages\starlette\routing.py", line 75, in app
    await response(scope, receive, send)
  File "D:\kevinzhang\tmp\MoneyPrinterTurbo\venv\lib\site-packages\starlette\responses.py", line 162, in __call__
    await self.background()
  File "D:\kevinzhang\tmp\MoneyPrinterTurbo\venv\lib\site-packages\starlette\background.py", line 45, in __call__
    await task()
  File "D:\kevinzhang\tmp\MoneyPrinterTurbo\venv\lib\site-packages\starlette\background.py", line 30, in __call__
    await run_in_threadpool(self.func, *self.args, **self.kwargs)
  File "D:\kevinzhang\tmp\MoneyPrinterTurbo\venv\lib\site-packages\starlette\concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "D:\kevinzhang\tmp\MoneyPrinterTurbo\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\kevinzhang\tmp\MoneyPrinterTurbo\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "D:\kevinzhang\tmp\MoneyPrinterTurbo\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "D:\kevinzhang\tmp\MoneyPrinterTurbo\app\services\task.py", line 155, in start
    video.generate_video(video_path=combined_video_path,
  File "D:\kevinzhang\tmp\MoneyPrinterTurbo\app\services\video.py", line 225, in generate_video
    sub = SubtitlesClip(subtitles=subtitle_path, make_textclip=generator, encoding='utf-8')
  File "D:\kevinzhang\tmp\MoneyPrinterTurbo\venv\lib\site-packages\moviepy\video\tools\subtitles.py", line 104, in __init__
    hasmask = bool(self.make_textclip("T").mask)
  File "D:\kevinzhang\tmp\MoneyPrinterTurbo\app\services\video.py", line 208, in generator
    clip = TextClip(
  File "<decorator-gen-76>", line 2, in __init__
  File "D:\kevinzhang\tmp\MoneyPrinterTurbo\venv\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "D:\kevinzhang\tmp\MoneyPrinterTurbo\venv\lib\site-packages\moviepy\video\VideoClip.py", line 1262, in __init__
    subprocess_call(cmd, logger=None)
  File "D:\kevinzhang\tmp\MoneyPrinterTurbo\venv\lib\site-packages\moviepy\tools.py", line 28, in subprocess_call
    logger(message="Moviepy - Running:\n>>> " + " ".join(cmd))
TypeError: sequence item 2: expected str instance, NoneType found
```

**Comment by KevinZhang19870314** [comment]
附上
[script.json](https://github.com/harry0703/MoneyPrinterTurbo/files/14902594/script.json)

**Comment by harry0703** [comment]
这个看起来是字幕的格式有问题，可以打开字幕看看是不是有多余的换行？
或者可以把 script.json 发出来看下

**Comment by KevinZhang19870314** [comment]
又换了一个subject，还是同样的错误。。。
[script.json](https://github.com/harry0703/MoneyPrinterTurbo/files/14902824/script.json)

**Comment by harry0703** [comment]
这2个文案，我这里生成音频和字幕都没有问题，你看看日志里面是否有类似这样的输出
```
completed, subtitle file created: /Users/harry/MoneyPrinterTurbo/storage/temp/tts.mp3.srt, duration: 94.662
```

有这个的话，就说明字幕是OK的

```
2024-04-08 15:54:46 | INFO | "./app\services\video.py:176": generate_video - start, video size: 1080 x 1920
2024-04-08 15:54:46 | INFO | "./app\services\video.py:177": generate_video -   ① video: D:\kevinzhang\tmp\MoneyPrinterTurbo\storage\tasks\c8448f7a-991d-465e-a1c3-d4203ce2380a\combined-1.mp4
2024-04-08 15:54:46 | INFO | "./app\services\video.py:178": generate_video -   ② audio: D:\kevinzhang\tmp\MoneyPrinterTurbo\storage\tasks\c8448f7a-991d-465e-a1c3-d4203ce2380a\audio.mp3
2024-04-08 15:54:46 | INFO | "./app\services\video.py:179": generate_video -   ③ subtitle: D:\kevinzhang\tmp\MoneyPrinterTurbo\storage\tasks\c8448f7a-991d-465e-a1c3-d4203ce2380a\subtitle.srt
2024-04-08 15:54:46 | INFO | "./app\services\video.py:180": generate_video -   ④ output: D:\kevinzhang\tmp\MoneyPrinterTurbo\storage\tasks\c8448f7a-991d-465e-a1c3-d4203ce2380a\final-1.mp4
```
可以把这几个文件，打包压缩后上传到这里，我定位一下原因

**Comment by KevinZhang19870314** [comment]
> 这2个文案，我这里生成音频和字幕都没有问题，你看看日志里面是否有类似这样的输出
> 
> ```
> completed, subtitle file created: /Users/harry/MoneyPrinterTurbo/storage/temp/tts.mp3.srt, duration: 94.662
> ```
> 
> 有这个的话，就说明字幕是OK的
> 
有这样的输出：
```
## generating subtitle, provider: edge
2024-04-08 16:40:26 | INFO | "./app\services\voice.py:1107": create_subtitle - completed, subtitle file created: D:\kevinzhang\tmp\MoneyPrinterTurbo\storage\tasks\bf97223b-7568-4dac-ad62-ba26a881037c\subtitle.srt, duration: 118.875
2024-04-08 16:40:26 | INFO | "./app\services\task.py:113": start - 
```

文件大于25M上传不了，我放到百度网盘了：
链接: https://pan.baidu.com/s/1OrEDkrlcw_eQUt3_imNkUA 
提取码: vmd1 

控制台log也附上。
[2024-04-08.txt](https://github.com/harry0703/MoneyPrinterTurbo/files/14903235/2024-04-08.txt)

我刚debug了下，的确有一个None。。。
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/13794286/2b1b1206-289f-489b-82a2-b2d46af51c18)

**Comment by harry0703** [comment]
发现问题了，这个是你的参数有错误
**`"text_background_color": null`**
把这个地方修改下应该就可以了

```json
"params": {
        "video_subject": "海底精彩，小鱼儿，深蓝色的海洋",
        "video_script": "",
        "video_terms": "",
        "video_aspect": "9:16",
        "video_concat_mode": "random",
        "video_clip_duration": 3,
        "video_count": 1,
        "video_language": "",
        "voice_name": "zh-CN-XiaoxiaoNeural-Female",
        "voice_volume": 1.0,
        "bgm_type": null,
        "bgm_file": null,
        "bgm_volume": 0.2,
        "subtitle_enabled": true,
        "subtitle_position": "bottom",
        "font_name": "STHeitiLight.ttc",
        "text_fore_color": "#FFFFFF",
        "text_background_color": null,
        "font_size": 60,
        "stroke_color": "#000000",
        "stroke_width": 1.5,
        "n_threads": null,
        "paragraph_number": null
    }
```

**Comment by KevinZhang19870314** [comment]
嗯 是的 但是我上周也是用的同样的参数没有问题，很奇怪，我现在用下面的参数试一下：
```
{
	"video_subject": "中国龙、龙的传人",
	"video_language": "",
	"video_script": "",
	"video_terms": "",
	"video_concat_mode": "random",
	"video_aspect": "9:16",
	"video_clip_duration": 3,
	"video_count": 1,
	"voice_name": "zh-CN-XiaoxiaoNeural-Female",
	"voice_volume": 1.0,
	"bgm_volume": 0.2,
	"subtitle_enabled": true,
	"font_name": "STHeitiLight.ttc",
	"subtitle_position": "bottom",
	"text_background_color": "transparent",
	"text_fore_color": "#FFFFFF",
	"font_size": 60,
	"stroke_color": "#000000",
	"stroke_width": 1.5
}
```

**Comment by KevinZhang19870314** [comment]
刚试了下，不报错了，谢谢！
