### ISSUE TITLE
使用localhost:3040经常提示使用u.s的vpn。但换了两个梯，都可以通过浏览器访问openai。并且在终端可以curl. www.google.com一下

### ISSUE THREAD

**Issue by iqilu2012** [harry0703/MoneyPrinterTurbo#209]
Traceback (most recent call last):
  File "/opt/anaconda3/bin/streamlit", line 5, in <module>
    from streamlit.web.cli import main
  File "/opt/anaconda3/lib/python3.11/site-packages/streamlit/__init__.py", line 69, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "/opt/anaconda3/lib/python3.11/site-packages/streamlit/delta_generator.py", line 35, in <module>
    from streamlit import (
  File "/opt/anaconda3/lib/python3.11/site-packages/streamlit/cursor.py", line 20, in <module>
    from streamlit.runtime.scriptrunner import get_script_run_ctx
  File "/opt/anaconda3/lib/python3.11/site-packages/streamlit/runtime/__init__.py", line 17, in <module>
    from streamlit.runtime.runtime import Runtime, RuntimeConfig, RuntimeState
  File "/opt/anaconda3/lib/python3.11/site-packages/streamlit/runtime/runtime.py", line 28, in <module>
    from streamlit.runtime.app_session import AppSession
  File "/opt/anaconda3/lib/python3.11/site-packages/streamlit/runtime/app_session.py", line 39, in <module>
    from streamlit.runtime import caching, legacy_caching
  File "/opt/anaconda3/lib/python3.11/site-packages/streamlit/runtime/caching/__init__.py", line 23, in <module>
    from streamlit.runtime.caching.cache_data_api import (
  File "/opt/anaconda3/lib/python3.11/site-packages/streamlit/runtime/caching/cache_data_api.py", line 34, in <module>
    from streamlit.runtime.caching.cache_utils import (
  File "/opt/anaconda3/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 32, in <module>
    from streamlit.elements.spinner import spinner
  File "/opt/anaconda3/lib/python3.11/site-packages/streamlit/elements/spinner.py", line 22, in <module>
    from streamlit.runtime.scriptrunner import add_script_run_ctx
ModuleNotFoundError: No module named 'streamlit.runtime.scriptrunner'

**Comment by harry0703** [comment]
因为GPT-3.5的免费使用，是通过绕过cloudflare的安全检测来实现的。有时候可能不稳当
你可以使用国内模型试试，moonshot，或者阿里通义千问等
