### ISSUE TITLE
请问一下为什么会报这个编码错误？

### ISSUE THREAD

**Issue by ChenKing2024** [harry0703/MoneyPrinterTurbo#22]
File "E:\AI Tools\MoneyPrinter\MoneyPrinterTurbo-main (1)\MoneyPrinterTurbo-main\app\services\video.py", line 184, in generate_video
    subtitles = SubtitlesClip(subtitles=subtitle_path, make_textclip=generator, encoding='utf-8')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SubtitlesClip.__init__() got an unexpected keyword argument 'encoding'
Exception ignored in: <function FFMPEG_AudioReader.__del__ at 0x000001DDBF618C20>
Traceback (most recent call last):
  File "D:\ProgramData\anaconda3\envs\MoneyPrinterTurbo\Lib\site-packages\moviepy\audio\io\readers.py", line 254, in __del__
    self.close_proc()
  File "D:\ProgramData\anaconda3\envs\MoneyPrinterTurbo\Lib\site-packages\moviepy\audio\io\readers.py", line 149, in close_proc
    self.proc.terminate()
  File "D:\ProgramData\anaconda3\envs\MoneyPrinterTurbo\Lib\subprocess.py", line 1671, in terminate
    _winapi.TerminateProcess(self._handle, 1)
OSError: [WinError 6] 句柄无效。

**Comment by harry0703** [comment]
看下 `requirements.txt` 文件，需要安装 `moviepy~=2.0.0.dev2` 版本，建议重新执行一下
```shell
pip install -r requirements.txt
```

**Comment by Ekko-G0d** [comment]
Exception ignored in: <function FFMPEG_AudioReader.__del__ at 0x0000015465F4C940>
Traceback (most recent call last):
  File "D:\2023go\AnaConda\envs\MoneyPrinterTurbo\lib\site-packages\moviepy\audio\io\readers.py", line 269, in __del__
    self.close()
  File "D:\2023go\AnaConda\envs\MoneyPrinterTurbo\lib\site-packages\moviepy\audio\io\readers.py", line 261, in close
    self.proc.terminate()
  File "D:\2023go\AnaConda\envs\MoneyPrinterTurbo\lib\subprocess.py", line 1589, in terminate
    _winapi.TerminateProcess(self._handle, 1)
OSError: [WinError 6] 句柄无效。

先由衷表示感谢！成功搭建并运行，但是有一些小问题：句柄无效问题，视频和音频成功拼接了，但是弹幕没能合成进去。

**Comment by harry0703** [comment]
建议项目路径中不要有 `中文`、`空格`之类的，可能会导致一些莫名其妙的问题
另外你可以复制更多一些异常信息么？这个有点看不出来

**Comment by Ekko-G0d** [comment]
> 建议项目路径中不要有 `中文`、`空格`之类的，可能会导致一些莫名其妙的问题 另外你可以复制更多一些异常信息么？这个有点看不出来

这个问题只出现了一次，现在好了。

根据我对项目的实际使用，发现根据关键词下载的视频并不是我想使用的，而我手中有想用的视频却不能添加的项目中。
希望大佬能增加一个对现有视频进行增减，然后再进行混剪的功能支持。

还有个建议可能比较复杂，就是根据文案的内容匹配视频，比如文案有一句出现了可爱的小猫，视频混剪片段也匹配小猫。

**Comment by harry0703** [comment]
@Ekko-G0d 您反馈的这个建议非常棒，也是计划中的，会优化
