### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by xunuoqing** [harry0703/MoneyPrinterTurbo#247]
## generating video: 1 => ./storage/tasks/a240439d-b011-484d-8aa8-a223665691ee/final-1.mp4
2024-04-12 16:01:33 | INFO | "./app/services/video.py:183": generate_video - start, video size: 1080 x 1920
2024-04-12 16:01:33 | INFO | "./app/services/video.py:184": generate_video -   ① video: ./storage/tasks/a240439d-b011-484d-8aa8-a223665691ee/combined-1.mp4
2024-04-12 16:01:33 | INFO | "./app/services/video.py:185": generate_video -   ② audio: ./storage/tasks/a240439d-b011-484d-8aa8-a223665691ee/audio.mp3
2024-04-12 16:01:33 | INFO | "./app/services/video.py:186": generate_video -   ③ subtitle: ./storage/tasks/a240439d-b011-484d-8aa8-a223665691ee/subtitle.srt
2024-04-12 16:01:33 | INFO | "./app/services/video.py:187": generate_video -   ④ output: ./storage/tasks/a240439d-b011-484d-8aa8-a223665691ee/final-1.mp4
2024-04-12 16:01:33 | INFO | "./app/services/video.py:202": generate_video - using font: ./resource/fonts/STHeitiLight.ttc
2024-04-12 16:01:34.052 Uncaught app exception
Traceback (most recent call last):
  File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
  File "/Users/xunuoqing/Downloads/MoneyPrinterTurbo-main/webui/Main.py", line 432, in <module>
    result = tm.start(task_id=task_id, params=params)
  File "/Users/xunuoqing/Downloads/MoneyPrinterTurbo-main/app/services/task.py", line 155, in start
    video.generate_video(video_path=combined_video_path,
  File "/Users/xunuoqing/Downloads/MoneyPrinterTurbo-main/app/services/video.py", line 238, in generate_video
    sub = SubtitlesClip(subtitles=subtitle_path, encoding='utf-8')
  File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/video/tools/subtitles.py", line 69, in __init__
    self.duration = max([tb for ((ta, tb), txt) in self.subtitles])
  File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/video/tools/subtitles.py", line 69, in <listcomp>
    self.duration = max([tb for ((ta, tb), txt) in self.subtitles])
TypeError: cannot unpack non-iterable NoneType object

[audio.mp3.json](https://github.com/harry0703/MoneyPrinterTurbo/files/14956044/audio.mp3.json)
[script.json](https://github.com/harry0703/MoneyPrinterTurbo/files/14956045/script.json)
[subtitle.srt.json](https://github.com/harry0703/MoneyPrinterTurbo/files/14956046/subtitle.srt.json)

**Comment by harry0703** [comment]
感谢反馈，已定位到原因，修复中
你也可以先将 `subtitle_provider` 配置为 `whisper` 使用（该模式下是正常的）

**Comment by harry0703** [comment]
已优化，更新代码即可
