### ISSUE TITLE
RuntimeError: Unsupported model binary version. 

### ISSUE THREAD

**Issue by rapatapa** [harry0703/MoneyPrinterTurbo#257]
## generating subtitle, provider: edge
2024-04-14 10:56:06 | ERROR | "./app\services\voice.py:1115": create_subtitle - failed, error: cannot unpack non-iterable NoneType object
2024-04-14 10:56:06 | WARNING | "./app\services\task.py:99": start - subtitle file not found, fallback to whisper
2024-04-14 10:56:06 | INFO | "./app\services\subtitle.py:26": create - loading model: ./models/whisper-large-v3, device: CPU, compute_type: int8
2024-04-14 10:56:06.338 Uncaught app exception
Traceback (most recent call last):
  File "F:\MoneyPrinterTurbo2\lib\python\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
  File "F:\MoneyPrinterTurbo2\MoneyPrinterTurbo\webui\Main.py", line 432, in <module>
    result = tm.start(task_id=task_id, params=params)
  File "F:\MoneyPrinterTurbo2\MoneyPrinterTurbo\app\services\task.py", line 102, in start
    subtitle.create(audio_file=audio_file, subtitle_file=subtitle_path)
  File "F:\MoneyPrinterTurbo2\MoneyPrinterTurbo\app\services\subtitle.py", line 27, in create
    model = WhisperModel(model_size_or_path=model_path,
  File "F:\MoneyPrinterTurbo2\lib\python\lib\site-packages\faster_whisper\transcribe.py", line 133, in __init__
    self.model = ctranslate2.models.Whisper(
RuntimeError: Unsupported model binary version. This executable supports models with binary version v6 or below, but the model has binary version v67324752. This usually means that the model was generated by a later version of CTranslate2. (Forward compatibility is not guaranteed.)

**Comment by harry0703** [comment]
Delete folder `./models/whisper-large-v3` and try again. 
It will download model from HuggingFace automatically.
Maybe it will works.
