### ISSUE TITLE
数组越界了？

### ISSUE THREAD

**Issue by javatomatos** [harry0703/MoneyPrinterTurbo#26]
![1](https://github.com/harry0703/MoneyPrinterTurbo/assets/72911887/15e4c25f-5e45-428e-97fc-10f8a5c04f4b)

**Comment by harry0703** [comment]
字幕生成失败了，优化了代码，可以更新后再试试

**Comment by vbc11** [comment]
2024-03-23 17:27:58.533 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\lolokj\anaconda3\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\lolokj\PycharmProjects\MoneyPrinterTurbo\webui\Main.py", line 225, in <module>
    tm.start(task_id=task_id, params=cfg)
  File "C:\Users\lolokj\PycharmProjects\MoneyPrinterTurbo\app\services\task.py", line 88, in start
    voice.create_subtitle(text=video_script, sub_maker=sub_maker, subtitle_file=subtitle_path)
  File "C:\Users\lolokj\PycharmProjects\MoneyPrinterTurbo\app\services\voice.py", line 69, in create_subtitle
    if sub_line == script_lines[sub_index]:
                   ~~~~~~~~~~~~^^^^^^^^^^^
IndexError: list index out of range

**Comment by 15050188022** [comment]
这个问题似乎依然存在，我也遇到了

**Comment by code101015** [comment]
我也遇到了

**Comment by JinguangHe** [comment]
同遇到

**Comment by wysstartgo** [comment]
一样，有问题

**Comment by harry0703** [comment]
感谢反馈
可以把  `./storage/tasks/{任务ID}` 目录下面的 `script.json` 发出来，帮助我定位一下问题吗？

**Comment by JinguangHe** [comment]
似乎是文案过长导致的，删了几句就可以运行了

**Comment by JinguangHe** [comment]
这个问题又出现了，现在删文案、关闭字幕都解决不了，每次都是生成combined-1.mp4后就报这个错
