### ISSUE TITLE
运行时报错类型错误

### ISSUE THREAD

**Issue by hy546880109** [harry0703/MoneyPrinterTurbo#327]
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/44777854/61fce9f2-cb9d-4d65-bbb8-2c4fe10a2de9)

2024-04-27 23:25:00.316 Uncaught app exception
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
  File "D:\DD\MoneyPrinterTurbo\webui\Main.py", line 33, in <module>
    from app.models.schema import VideoParams, VideoAspect, VideoConcatMode, MaterialInfo
  File "D:\DD\MoneyPrinterTurbo\app\models\schema.py", line 82, in <module>
    class VideoParams(BaseModel):
  File "D:\DD\MoneyPrinterTurbo\app\models\schema.py", line 98, in VideoParams
    video_terms: Optional[str | list] = None  # 用于生成视频的关键词
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by hy546880109** [comment]
问题解决了，没有启动虚拟环境
