### ISSUE TITLE
Error: 'model_not_found'

### ISSUE THREAD

**Issue by czqasngit** [harry0703/MoneyPrinterTurbo#4]
Traceback (most recent call last):
  File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
  File "/Volumes/Work/GitHub/MoneyPrinterTurbo/webui/Main.py", line 153, in <module>
    tm.start(task_id=task_id, params=cfg)
  File "/Volumes/Work/GitHub/MoneyPrinterTurbo/app/services/task.py", line 45, in start
    script = gpt.generate_script(video_subject=video_subject, language=language, paragraph_number=paragraph_number)
  File "/Volumes/Work/GitHub/MoneyPrinterTurbo/app/services/gpt.py", line 64, in generate_script
    response = _generate_response(prompt=prompt)
  File "/Volumes/Work/GitHub/MoneyPrinterTurbo/app/services/gpt.py", line 29, in _generate_response
    response = openai.chat.completions.create(
  File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/openai/_utils/_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 663, in create
    return self._post(
  File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/openai/_base_client.py", line 1200, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/openai/_base_client.py", line 889, in request
    return self._request(
  File "/opt/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/openai/_base_client.py", line 980, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4-0125-preview` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

**Comment by harry0703** [comment]
```
The model gpt-4-0125-preview does not exist or you do not have access to it
```
看起来是你没有 `gpt-4-0125-preview` 模型的**访问权限**，你需要到 `OPENAI` 的后台确认一下

**Comment by czqasngit** [comment]
咨询一下，我应该怎么确认呢？有没有教程
