### ISSUE TITLE
新版本会报 导入task失败，屏蔽可以正常运行，但是无法生成视频

### ISSUE THREAD

**Issue by ganfengbao** [harry0703/MoneyPrinterTurbo#41]

**Comment by harry0703** [comment]
可以看下详细的错误么？是Windows系统？
你看看执行 webui.bat  的时候，打印出来的  
```
***** Current directory: XXXXXXXXXX
```
路径，是你当前项目的路径么？

或者可以改下这个地方试试看能不能解决
```
set PYTHONPATH=你的绝对路径
```

**Comment by ganfengbao** [comment]
2024-03-22 22:26:02.979 Uncaught app exception
Traceback (most recent call last):
  File "E:\soft\install\conda\envs\MoneyPrinterTurbo\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
  File "E:\soft\MoneyPrinterTurbo\webui\Main.py", line 9, in <module>
    from app.services import task, llm
  File "E:\soft\MoneyPrinterTurbo\app\services\task.py", line 9, in <module>
    from app.services import llm, material, voice, video, subtitle
  File "E:\soft\MoneyPrinterTurbo\app\services\material.py", line 16, in <module>
    raise ValueError("pexels_api_keys is not set, please set it in the config.toml file.")
ValueError: pexels_api_keys is not set, please set it in the config.toml file.
2024-03-22 22:26:02.980 Uncaught app exception
Traceback (most recent call last):
  File "E:\soft\install\conda\envs\MoneyPrinterTurbo\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
  File "E:\soft\MoneyPrinterTurbo\webui\Main.py", line 9, in <module>
    from app.services import task, llm
ImportError: cannot import name 'task' from 'app.services' (E:\soft\MoneyPrinterTurbo\app\services\__init__.py)

启动时候报的这个问题，是用webui.bat启动的，在anconda环境下

**Comment by harry0703** [comment]
> ValueError: pexels_api_keys is not set, please set it in the config.toml file.

是这个错误引起的，你需要先设置 **pexels_api_keys**，比如 
```
pexels_api_keys = ["123456789","abcdefghi"]
```

**Comment by ganfengbao** [comment]
> > ValueError: pexels_api_keys is not set, please set it in the config.toml file.
> 
> 是这个错误引起的，你需要先设置 **pexels_api_keys**，比如
> 
> ```
> pexels_api_keys = ["123456789","abcdefghi"]
> ```

确实是这个问题，已经可以了，多谢
