### ISSUE TITLE
TypeError: must be real number, not NoneType

### ISSUE THREAD

**Issue by wx953999109** [harry0703/MoneyPrinterTurbo#423]
【my debug log】
2024-06-23 19:53:34.218 | INFO     | app.services.video:combine_videos:121 - writing

2024-06-23 19:53:34.221 | INFO     | app.services.video:combine_videos:123 - combined_video_path: .\storage\tasks\f0a44567-382c-4035-adfd-3448b28a6171\combined-1.mp4

2024-06-23 19:53:34.222 | INFO     | app.services.video:combine_videos:124 - threads: 2

2024-06-23 19:53:34.223 | INFO     | app.services.video:combine_videos:125 - temp_audiofile_path: .\storage\tasks\f0a44567-382c-4035-adfd-3448b28a6171

2024-06-23 19:53:34.224 | INFO     | app.services.video:combine_videos:126 - audio_codec: aac

2024-06-23 19:53:34.225 | INFO     | app.services.video:combine_videos:127 - fps: 30

【full log】
2024-06-23 20:06:30 | INFO | "./app\services\task.py:168": start -

## combining video: 1 => .\storage\tasks\06ab6085-ef75-43a2-9a00-fb2188fa982a\combined-1.mp4
2024-06-23 20:06:31 | INFO | "./app\services\video.py:40": combine_videos - max duration of audio: 42.38 seconds
2024-06-23 20:06:31 | INFO | "./app\services\video.py:44": combine_videos - each clip will be maximum 3 seconds long
2024-06-23 20:07:07 | INFO | "./app\services\video.py:111": combine_videos - resizing video to 1080 x 1920, clip size: 720 x 1280
E:\ai\MoneyPrinterTurbo-Portable-Windows-1.1.9\lib\python\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:154: UserWarning: In file E:\ai\MoneyPrinterTurbo-Portable-Windows-1.1.9\MoneyPrinterTurbo\storage\cache_videos/vid-5f17d43c682974a8772f0484c5ebc82b.mp4, 6220800 bytes wanted but 0 bytes read,at frame index 359 (out of a total 360 frames), at time 14.97/15.02 sec. Using the last valid frame instead.
  warnings.warn(
2024-06-23 20:07:18 | INFO | "./app\services\video.py:111": combine_videos - resizing video to 1080 x 1920, clip size: 720 x 1280
2024-06-23 20:07:21 | INFO | "./app\services\video.py:111": combine_videos - resizing video to 1080 x 1920, clip size: 720 x 1280
2024-06-23 20:07:25 | INFO | "./app\services\video.py:121": combine_videos - writing
2024-06-23 20:07:25 | INFO | "./app\services\video.py:123": combine_videos - combined_video_path: .\storage\tasks\06ab6085-ef75-43a2-9a00-fb2188fa982a\combined-1.mp4
2024-06-23 20:07:25 | INFO | "./app\services\video.py:124": combine_videos - threads: 2
2024-06-23 20:07:25 | INFO | "./app\services\video.py:125": combine_videos - temp_audiofile_path: .\storage\tasks\06ab6085-ef75-43a2-9a00-fb2188fa982a
2024-06-23 20:07:25 | INFO | "./app\services\video.py:126": combine_videos - audio_codec: aac
2024-06-23 20:07:25 | INFO | "./app\services\video.py:127": combine_videos - fps: 30
Moviepy - Building video E:\ai\MoneyPrinterTurbo-Portable-Windows-1.1.9\MoneyPrinterTurbo\storage\tasks\06ab6085-ef75-43a2-9a00-fb2188fa982a\combined-1.mp4.
Moviepy - Writing video E:\ai\MoneyPrinterTurbo-Portable-Windows-1.1.9\MoneyPrinterTurbo\storage\tasks\06ab6085-ef75-43a2-9a00-fb2188fa982a\combined-1.mp4

2024-06-23 20:07:25.392 Uncaught app exception
Traceback (most recent call last):
  File "E:\ai\MoneyPrinterTurbo-Portable-Windows-1.1.9\lib\python\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
  File "E:\ai\MoneyPrinterTurbo-Portable-Windows-1.1.9\MoneyPrinterTurbo\webui\Main.py", line 637, in <module>
    result = tm.start(task_id=task_id, params=params)
  File "E:\ai\MoneyPrinterTurbo-Portable-Windows-1.1.9\MoneyPrinterTurbo\app\services\task.py", line 169, in start
    video.combine_videos(combined_video_path=combined_video_path,
  File "E:\ai\MoneyPrinterTurbo-Portable-Windows-1.1.9\MoneyPrinterTurbo\app\services\video.py", line 130, in combine_videos
    video_clip.write_videofile(filename=combined_video_path,
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "E:\ai\MoneyPrinterTurbo-Portable-Windows-1.1.9\lib\python\lib\site-packages\moviepy\decorators.py", line 56, in requires_duration
    return f(clip, *a, **k)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "E:\ai\MoneyPrinterTurbo-Portable-Windows-1.1.9\lib\python\lib\site-packages\moviepy\decorators.py", line 135, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "E:\ai\MoneyPrinterTurbo-Portable-Windows-1.1.9\lib\python\lib\site-packages\moviepy\decorators.py", line 24, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "E:\ai\MoneyPrinterTurbo-Portable-Windows-1.1.9\lib\python\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "E:\ai\MoneyPrinterTurbo-Portable-Windows-1.1.9\lib\python\lib\site-packages\moviepy\video\VideoClip.py", line 343, in write_videofile
    ffmpeg_write_video(
  File "E:\ai\MoneyPrinterTurbo-Portable-Windows-1.1.9\lib\python\lib\site-packages\moviepy\video\io\ffmpeg_writer.py", line 243, in ffmpeg_write_video
    with FFMPEG_VideoWriter(
  File "E:\ai\MoneyPrinterTurbo-Portable-Windows-1.1.9\lib\python\lib\site-packages\moviepy\video\io\ffmpeg_writer.py", line 111, in __init__
    "%.02f" % fps,
TypeError: must be real number, not NoneType

**Comment by harry0703** [comment]
I checked this against the current main branch.

This traceback comes from the older combine_videos implementation that wrote the merged clip through MoviePy and could end up passing an invalid or missing fps value into the final writer. The current main branch no longer uses that old path:
- the merge pipeline now uses a single ffmpeg concat step for clip concatenation
- the project also uses an explicit module-level fps setting in the video pipeline instead of relying on that older dynamic path

Because this issue is tied to the previous combine implementation, I am closing it as fixed by the current codebase.
