### ISSUE TITLE
格式问题

### ISSUE THREAD

**Issue by vbc11** [harry0703/MoneyPrinterTurbo#45]
2024-03-23 17:36:18.765 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\lolokj\anaconda3\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\lolokj\PycharmProjects\MoneyPrinterTurbo\webui\Main.py", line 225, in <module>
    tm.start(task_id=task_id, params=cfg)
  File "C:\Users\lolokj\PycharmProjects\MoneyPrinterTurbo\app\services\task.py", line 135, in start
    video.generate_video(video_path=combined_video_path,
  File "C:\Users\lolokj\PycharmProjects\MoneyPrinterTurbo\app\services\video.py", line 180, in generate_video
    subtitles = SubtitlesClip(subtitles=subtitle_path, make_textclip=generator, encoding='utf-8')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SubtitlesClip.__init__() got an unexpected keyword argument 'encoding'

**Comment by harry0703** [comment]
安装一下依赖就行了，这个是moviepy的版本不对导致的报错

```
pip install -r requirements.txt
```

**Comment by wsk3373** [comment]
我已经执行过这个命令。(MoneyPrinterTurbo) PS C:\Users\Administrator\github\MoneyPrinterTurbo> pip list | findstr moviepy
moviepy                   2.0.0.dev2
还是这个问题。并没有解决

**Comment by harry0703** [comment]
moviepy 2.0.0 应该是正确的。实在不行，你修改下代码试试

```python
#C:\Users\lolokj\PycharmProjects\MoneyPrinterTurbo\app\services\video.py"
# line 180, in generate_video

# 将
subtitles = SubtitlesClip(subtitles=subtitle_path, make_textclip=generator, encoding='utf-8')'
# 改成
subtitles = SubtitlesClip(subtitles=subtitle_path, make_textclip=generator)

```

**Comment by wsk3373** [comment]
好的，谢谢你的回复我试一下。
