### ISSUE TITLE
保存视频出错

### ISSUE THREAD

**Issue by lgao-matax** [harry0703/MoneyPrinterTurbo#531]
项目是main 分支，moviepy 1.0.2 版本保存视频时 报错：
2024-11-21 16:04:34 | INFO | "./app/services/video.py:118": combine_videos - resizing video to 1080 x 1920, clip size: 3840 x 2160
2024-11-21 16:04:34.722 Uncaught app exception
Traceback (most recent call last):
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
  File "/mnt/data/lgao/MoneyPrinterTurbo/webui/Main.py", line 787, in <module>
    result = tm.start(task_id=task_id, params=params)
  File "/mnt/data/lgao/MoneyPrinterTurbo/app/services/task.py", line 299, in start
    final_video_paths, combined_video_paths = generate_final_videos(
  File "/mnt/data/lgao/MoneyPrinterTurbo/app/services/task.py", line 176, in generate_final_videos
    video.combine_videos(
  File "/mnt/data/lgao/MoneyPrinterTurbo/app/services/video.py", line 80, in combine_videos
    clip = clip.subclip(0, (audio_duration - video_duration))
  File "<decorator-gen-35>", line 2, in subclip
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "<decorator-gen-34>", line 2, in subclip
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/decorators.py", line 29, in apply_to_mask
    newclip = f(clip, *a, **k)
  File "<decorator-gen-33>", line 2, in subclip
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/decorators.py", line 41, in apply_to_audio
    newclip = f(clip, *a, **k)
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/Clip.py", line 389, in subclip
    newclip = self.fl_time(lambda t: t + t_start, apply_to=[])
    newclip = self.fl_time(lambda t: t + t_start, apply_to=[])
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/Clip.py", line 187, in fl_time
    return self.fl(lambda gf, t: gf(t_func(t)), apply_to,
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/Clip.py", line 136, in fl
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "<decorator-gen-57>", line 2, in set_make_frame
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/decorators.py", line 14, in outplace
    f(newclip, *a, **k)
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/video/VideoClip.py", line 644, in set_make_frame
    self.size = self.get_frame(0).shape[:2][::-1]
  File "<decorator-gen-10>", line 2, in get_frame
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/Clip.py", line 93, in get_frame
    return self.make_frame(t)
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/Clip.py", line 136, in <lambda>
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/Clip.py", line 187, in <lambda>
    return self.fl(lambda gf, t: gf(t_func(t)), apply_to,
  File "<decorator-gen-10>", line 2, in get_frame
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/Clip.py", line 93, in get_frame
    return self.make_frame(t)
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/Clip.py", line 136, in <lambda>
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/Clip.py", line 187, in <lambda>
    return self.fl(lambda gf, t: gf(t_func(t)), apply_to,
  File "<decorator-gen-10>", line 2, in get_frame
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/Clip.py", line 93, in get_frame
    return self.make_frame(t)
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/video/io/VideoFileClip.py", line 113, in <lambda>
    self.make_frame = lambda t: self.reader.get_frame(t)
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/video/io/ffmpeg_reader.py", line 184, in get_frame
    result = self.read_frame()
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/video/io/ffmpeg_reader.py", line 133, in read_frame
    raise IOError(("MoviePy error: failed to read the first frame of "
OSError: MoviePy error: failed to read the first frame of video file /mnt/data/lgao/MoneyPrinterTurbo/storage/cache_videos/vid-93aa777c6bba73f50d3a34beee693020.mp4. That might mean that the file is corrupted. That may also mean that you are using a deprecated version of FFMPEG. On Ubuntu/Debian for instance the version in the repos is deprecated. Please update to a recent version from the website.
imageio-ffmpeg 版本是：0.5.1
 ffmpeg 7:4.2.7-0ubuntu0.1

**Comment by lgao-matax** [comment]
当使用moviepy 1.0.3 版本 出错：
```
2024-11-21 16:27:22 | INFO | "./app/services/video.py:217": generate_video -   ④ output: ./storage/tasks/03d3db74-50d7-44b3-8864-ddbe5e408d09/final-1.mp4
2024-11-21 16:27:22 | INFO | "./app/services/video.py:232": generate_video - using font: ./resource/fonts/STHeitiLight.ttc
2024-11-21 16:27:22.717 Uncaught app exception
Traceback (most recent call last):
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/video/VideoClip.py", line 1137, in __init__
    subprocess_call(cmd, logger=None)
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/tools.py", line 54, in subprocess_call
    raise IOError(err.decode('utf8'))
OSError: convert-im6.q16: attempt to perform an operation not allowed by the security policy `@/tmp/tmpjrftxgk4.txt' @ error/property.c/InterpretImageProperties/3668.
convert-im6.q16: no images defined `PNG32:/tmp/tmp5by8tpmk.png' @ error/convert.c/ConvertImageCommand/3258.
```



但是 imagemagick是安装了的 ubuntu20.04 系统

**Comment by lgao-matax** [comment]
上面1.0.3的 imagemagick 权限问题解决了 但是报这个错误：2024-11-21 17:19:33 | INFO | "./app/services/video.py:232": generate_video - using font: ./resource/fonts/STHeitiLight.ttc
2024-11-21 17:19:33.571 Uncaught app exception
Traceback (most recent call last):
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 74, in write_frames
    self.proc.stdin.write(frames_array.tobytes())
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
  File "/mnt/data/lgao/MoneyPrinterTurbo/webui/Main.py", line 787, in <module>
    result = tm.start(task_id=task_id, params=params)
  File "/mnt/data/lgao/MoneyPrinterTurbo/app/services/task.py", line 299, in start
    final_video_paths, combined_video_paths = generate_final_videos(
  File "/mnt/data/lgao/MoneyPrinterTurbo/app/services/task.py", line 192, in generate_final_videos
    video.generate_video(
  File "/mnt/data/lgao/MoneyPrinterTurbo/app/services/video.py", line 293, in generate_video
    video_clip.write_videofile(
  File "<decorator-gen-51>", line 2, in write_videofile
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-50>", line 2, in write_videofile
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/decorators.py", line 135, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "<decorator-gen-49>", line 2, in write_videofile
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/video/VideoClip.py", line 293, in write_videofile
    self.audio.write_audiofile(audiofile, audio_fps,
  File "<decorator-gen-73>", line 2, in write_audiofile
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/audio/AudioClip.py", line 206, in write_audiofile
    return ffmpeg_audiowrite(self, filename, fps, nbytes, buffersize,
  File "<decorator-gen-70>", line 2, in ffmpeg_audiowrite
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 170, in ffmpeg_audiowrite
    writer.write_frames(chunk)
  File "/home/lgao/anaconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 117, in write_frames
    raise IOError(error)
OSError: [Errno 32] Broken pipe

MoviePy error: FFMPEG encountered the following error while writing file /mnt/data/lgao/MoneyPrinterTurbo/storage/tasks/ef53738d-7fa8-4830-8dd2-56d2c1dc6f94:

b"[NULL @ 0x6568680] Unable to find a suitable output format for '/mnt/data/lgao/MoneyPrinterTurbo/storage/tasks/ef53738d-7fa8-4830-8dd2-56d2c1dc6f94'\n/mnt/data/lgao/MoneyPrinterTurbo/storage/tasks/ef53738d-7fa8-4830-8dd2-56d2c1dc6f94: Invalid argument\n"

In case it helps, make sure you are using a recent version of FFMPEG (the versions in the Ubuntu/Debian repos are deprecated).

ffmpeg  自己编译成了6.0 的版本 还是不行

**Comment by lgao-matax** [comment]
moviepy 升级到2.0.0 手动改动  video.py 中的函数接口 也报在写文件时候报错；你们咋跑通的呢？

**Comment by yyhhyyyyyy** [comment]
Please pull the latest code to access the fix.
