### ISSUE TITLE
AttributeError: 'VideoFileClip' object has no attribute 'subclip' in MoviePy 2.0.0

### ISSUE THREAD

**Issue by giannis88** [harry0703/MoneyPrinterTurbo#532]
(.venv) PS C:\Users\giova\MoneyPrinterTurbo> streamlit run webui/Main.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.0.139:8501

******** sys.path ********
['webui/Main.py', 'webui', 'C:\\Python312\\Scripts\\streamlit.exe', 'C:\\Python312\\python312.zip', 'C:\\Python312\\DLLs', 'C:\\Python312\\Lib', 'C:\\Python312', 'C:\\Users\\giova\\AppData\\Roaming\\Python\\Python312\\site-packages', 'C:\\Python312\\Lib\\site-packages', 'C:\\Python312\\Lib\\site-packages\\win32', 'C:\\Python312\\Lib\\site-packages\\win32\\lib', 'C:\\Python312\\Lib\\site-packages\\Pythonwin', 'C:\\Users\\giova\\MoneyPrinterTurbo']

2024-11-21 17:14:56.320 | INFO     | app.config.config:load_config:22 - load config from file: C:\Users\giova\MoneyPrinterTurbo/config.toml
2024-11-21 17:14:56.321 | INFO     | app.config.config:<module>:70 - MoneyPrinterTurbo v1.2.1
2024-11-21 17:15:40 | INFO | "./app\services\llm.py:282": generate_script - subject: finances
2024-11-21 17:15:40 | INFO | "./app\services\llm.py:18": _generate_response - llm provider: ollama
2024-11-21 17:15:47 | SUCCESS | "./app\services\llm.py:323": generate_script - completed:
Welcome to your financial well-being guide. Understanding your monthly budget and tracking expenses is crucial for managing your finances effectively. Firstly, assess all sources of income to see how much money comes in each month. Then, list your fixed costs such as rent or mortgage, utilities, and car payments. Next, categorize variable expenses like groceries, entertainment, and clothes. It's important to allocate a portion of your budget for savings and investments to ensure financial stability. Regularly review and adjust your budget to keep your finances in check. Stay organized and proactive to take control of your financial future.
2024-11-21 17:15:47 | INFO | "./app\services\llm.py:354": generate_terms - subject: finances
2024-11-21 17:15:47 | INFO | "./app\services\llm.py:18": _generate_response - llm provider: ollama
2024-11-21 17:15:50 | SUCCESS | "./app\services\llm.py:384": generate_terms - completed:
['Monthly budget analysis', 'Expense tracking software', 'Financial stability tips', 'Savings and investment strategies', 'Budget review and adjustments']
2024-11-21 17:15:57 | INFO | "./webui\Main.py:783": <module> - Start Generating Video
2024-11-21 17:15:57 | INFO | "./webui\Main.py:784": <module> - {
    "video_subject": "finances",
    "video_script": "Welcome to your financial well-being guide. Understanding your monthly budget and tracking expenses is crucial for managing your finances effectively. Firstly, assess all sources of income to see how much money comes in each month. Then, list your fixed costs such as rent or mortgage, utilities, and car payments. Next, categorize variable expenses like groceries, entertainment, and clothes. It's important to allocate a portion of your budget for savings and investments to ensure financial stability. Regularly review and adjust your budget to keep your finances in check. Stay organized and proactive to take control of your financial future.",
    "video_terms": "Monthly budget analysis, Expense tracking software, Financial stability tips, Savings and investment strategies, Budget review and adjustments",
    "video_aspect": "9:16",
    "video_concat_mode": "random",
    "video_clip_duration": 3,
    "video_count": 1,
    "video_source": "pixabay",
    "video_materials": null,
    "video_language": "",
    "voice_name": "en-US-AnaNeural-Female",
    "voice_volume": 1.0,
    "voice_rate": 1.0,
    "bgm_type": "random",
    "bgm_file": "",
    "bgm_volume": 0.2,
    "subtitle_enabled": true,
    "subtitle_position": "bottom",
    "custom_position": 70.0,
    "font_name": "MicrosoftYaHeiBold.ttc",
    "text_fore_color": "#FFFFFF",
    "text_background_color": "transparent",
    "font_size": 60,
    "stroke_color": "#000000",
    "stroke_width": 1.5,
    "n_threads": 2,
    "paragraph_number": 1
}
2024-11-21 17:15:57 | INFO | "./app\services\task.py:210": start - start task: 17e3810f-031e-4a7b-aa7e-134dd5bec899, stop_at: video
2024-11-21 17:15:57 | INFO | "./app\services\task.py:18": generate_script -

## generating video script
2024-11-21 17:15:57 | DEBUG | "./app\services\task.py:27": generate_script - video script:
Welcome to your financial well-being guide. Understanding your monthly budget and tracking expenses is crucial for managing your finances effectively. Firstly, assess all sources of income to see how much money comes in each month. Then, list your fixed costs such as rent or mortgage, utilities, and car payments. Next, categorize variable expenses like groceries, entertainment, and clothes. It's important to allocate a portion of your budget for savings and investments to ensure financial stability. Regularly review and adjust your budget to keep your finances in check. Stay organized and proactive to take control of your financial future.
2024-11-21 17:15:57 | INFO | "./app\services\task.py:38": generate_terms -

## generating video terms
2024-11-21 17:15:57 | DEBUG | "./app\services\task.py:52": generate_terms - video terms: [
    "Monthly budget analysis",
    "Expense tracking software",
    "Financial stability tips",
    "Savings and investment strategies",
    "Budget review and adjustments"
]
2024-11-21 17:15:57 | INFO | "./app\services\task.py:75": generate_audio -

## generating audio
2024-11-21 17:15:57 | INFO | "./app\services\voice.py:1057": azure_tts_v1 - start, voice name: en-US-AnaNeural, try: 1
2024-11-21 17:16:01 | INFO | "./app\services\voice.py:1077": azure_tts_v1 - completed, output file: .\storage\tasks\17e3810f-031e-4a7b-aa7e-134dd5bec899\audio.mp3
2024-11-21 17:16:01 | INFO | "./app\services\task.py:103": generate_subtitle -

## generating subtitle, provider: edge
2024-11-21 17:16:01 | INFO | "./app\services\voice.py:1262": create_subtitle - completed, subtitle file created: .\storage\tasks\17e3810f-031e-4a7b-aa7e-134dd5bec899\subtitle.srt, duration: 48.65
2024-11-21 17:16:01 | INFO | "./app\services\task.py:141": get_video_materials -

## downloading videos from pixabay
2024-11-21 17:16:01 | INFO | "./app\services\material.py:109": search_videos_pixabay - searching videos: https://pixabay.com/api/videos/?q=Monthly+budget+analysis&video_type=all&per_page=50&key=47196446-75936fb8d3f4807b11d21921a, with proxies: {}
2024-11-21 17:16:02 | INFO | "./app\services\material.py:215": download_videos - found 50 videos for 'Monthly budget analysis'
2024-11-21 17:16:02 | INFO | "./app\services\material.py:109": search_videos_pixabay - searching videos: https://pixabay.com/api/videos/?q=Expense+tracking+software&video_type=all&per_page=50&key=47196446-75936fb8d3f4807b11d21921a, with proxies: {}
2024-11-21 17:16:02 | INFO | "./app\services\material.py:215": download_videos - found 50 videos for 'Expense tracking software'
2024-11-21 17:16:02 | INFO | "./app\services\material.py:109": search_videos_pixabay - searching videos: https://pixabay.com/api/videos/?q=Financial+stability+tips&video_type=all&per_page=50&key=47196446-75936fb8d3f4807b11d21921a, with proxies: {}
2024-11-21 17:16:02 | INFO | "./app\services\material.py:215": download_videos - found 50 videos for 'Financial stability tips'
2024-11-21 17:16:02 | INFO | "./app\services\material.py:109": search_videos_pixabay - searching videos: https://pixabay.com/api/videos/?q=Savings+and+investment+strategies&video_type=all&per_page=50&key=47196446-75936fb8d3f4807b11d21921a, with proxies: {}
2024-11-21 17:16:03 | INFO | "./app\services\material.py:215": download_videos - found 50 videos for 'Savings and investment strategies'
2024-11-21 17:16:03 | INFO | "./app\services\material.py:109": search_videos_pixabay - searching videos: https://pixabay.com/api/videos/?q=Budget+review+and+adjustments&video_type=all&per_page=50&key=47196446-75936fb8d3f4807b11d21921a, with proxies: {}
2024-11-21 17:16:03 | INFO | "./app\services\material.py:215": download_videos - found 49 videos for 'Budget review and adjustments'
2024-11-21 17:16:03 | INFO | "./app\services\material.py:223": download_videos - found total videos: 220, required duration: 49 seconds, found duration: 3513.0 seconds
2024-11-21 17:16:03 | INFO | "./app\services\material.py:240": download_videos - downloading video: https://cdn.pixabay.com/video/2021/09/13/88502-606110701_large.mp4
2024-11-21 17:16:04 | INFO | "./app\services\material.py:245": download_videos - video saved: .\storage\cache_videos/vid-204aec1e42b30fc74a672ef0c0194a9a.mp4
2024-11-21 17:16:04 | INFO | "./app\services\material.py:240": download_videos - downloading video: https://cdn.pixabay.com/video/2023/11/29/191304-889685064_large.mp4
2024-11-21 17:16:05 | INFO | "./app\services\material.py:245": download_videos - video saved: .\storage\cache_videos/vid-52eb53999073f44a677db069a2cff3a3.mp4
2024-11-21 17:16:05 | INFO | "./app\services\material.py:240": download_videos - downloading video: https://cdn.pixabay.com/video/2022/03/29/112256-693798366_large.mp4
2024-11-21 17:16:06 | INFO | "./app\services\material.py:245": download_videos - video saved: .\storage\cache_videos/vid-54f6b5579925d3df689501b7b08218fe.mp4
2024-11-21 17:16:06 | INFO | "./app\services\material.py:240": download_videos - downloading video: https://cdn.pixabay.com/video/2020/04/07/35255-407130682_large.mp4
2024-11-21 17:16:10 | INFO | "./app\services\material.py:245": download_videos - video saved: .\storage\cache_videos/vid-6c75f7240f9200a12ffeea94cc493bfd.mp4
2024-11-21 17:16:10 | INFO | "./app\services\material.py:240": download_videos - downloading video: https://cdn.pixabay.com/video/2017/07/23/10847-226632926_large.mp4
2024-11-21 17:16:11 | INFO | "./app\services\material.py:245": download_videos - video saved: .\storage\cache_videos/vid-f3052bbd9018357b4178aef67f9c147e.mp4
2024-11-21 17:16:11 | INFO | "./app\services\material.py:240": download_videos - downloading video: https://cdn.pixabay.com/video/2016/09/21/5364-183788428_medium.mp4
2024-11-21 17:16:12 | INFO | "./app\services\material.py:245": download_videos - video saved: .\storage\cache_videos/vid-939a1dac27f6a40726068b6cc1a89b16.mp4
2024-11-21 17:16:12 | INFO | "./app\services\material.py:240": download_videos - downloading video: https://cdn.pixabay.com/video/2022/10/24/136283-764387738_large.mp4
2024-11-21 17:16:14 | INFO | "./app\services\material.py:245": download_videos - video saved: .\storage\cache_videos/vid-afd074d0b29b38dbd63d4e6f3691dca1.mp4
2024-11-21 17:16:14 | INFO | "./app\services\material.py:240": download_videos - downloading video: https://cdn.pixabay.com/video/2016/09/21/5357-184226666_medium.mp4
2024-11-21 17:16:14 | INFO | "./app\services\material.py:245": download_videos - video saved: .\storage\cache_videos/vid-6075c4fb7aae360946a8c768ffcea9d0.mp4
2024-11-21 17:16:14 | INFO | "./app\services\material.py:240": download_videos - downloading video: https://cdn.pixabay.com/video/2018/03/17/15055-260649461_large.mp4
2024-11-21 17:16:15 | INFO | "./app\services\material.py:245": download_videos - video saved: .\storage\cache_videos/vid-b9783a60b87a5513a6f902bd36b5e899.mp4
2024-11-21 17:16:15 | INFO | "./app\services\material.py:240": download_videos - downloading video: https://cdn.pixabay.com/video/2024/02/15/200619-913173295_large.mp4
2024-11-21 17:16:17 | INFO | "./app\services\material.py:245": download_videos - video saved: .\storage\cache_videos/vid-42d03f890e0503232930cd9ab218aab5.mp4
2024-11-21 17:16:17 | INFO | "./app\services\material.py:240": download_videos - downloading video: https://cdn.pixabay.com/video/2023/08/23/177347-857376739_large.mp4
2024-11-21 17:16:20 | INFO | "./app\services\material.py:245": download_videos - video saved: .\storage\cache_videos/vid-df7243b522b12ed137ae9a7f4ffcc58e.mp4
2024-11-21 17:16:20 | INFO | "./app\services\material.py:240": download_videos - downloading video: https://cdn.pixabay.com/video/2017/11/04/12751-241674238_large.mp4
2024-11-21 17:16:21 | INFO | "./app\services\material.py:245": download_videos - video saved: .\storage\cache_videos/vid-dd8de336191d73cc19bf4901d317937a.mp4
2024-11-21 17:16:21 | INFO | "./app\services\material.py:240": download_videos - downloading video: https://cdn.pixabay.com/video/2023/07/25/173138-848555632_large.mp4
2024-11-21 17:16:24 | INFO | "./app\services\material.py:245": download_videos - video saved: .\storage\cache_videos/vid-dc935302f37fa6bde16c66c97c413753.mp4
2024-11-21 17:16:24 | INFO | "./app\services\material.py:240": download_videos - downloading video: https://cdn.pixabay.com/video/2024/03/15/204306-923909642_large.mp4
2024-11-21 17:16:24 | INFO | "./app\services\material.py:161": save_video - video already exists: .\storage\cache_videos/vid-72ee0a89df780e7175dcc513821c62b1.mp4
2024-11-21 17:16:24 | INFO | "./app\services\material.py:245": download_videos - video saved: .\storage\cache_videos/vid-72ee0a89df780e7175dcc513821c62b1.mp4
2024-11-21 17:16:24 | INFO | "./app\services\material.py:240": download_videos - downloading video: https://cdn.pixabay.com/video/2016/09/21/5539-184226951_medium.mp4
2024-11-21 17:16:24 | INFO | "./app\services\material.py:245": download_videos - video saved: .\storage\cache_videos/vid-698923e4e60d7ff07183aa25c1c06563.mp4
2024-11-21 17:16:24 | INFO | "./app\services\material.py:240": download_videos - downloading video: https://cdn.pixabay.com/video/2018/09/26/18439-292228582_large.mp4
2024-11-21 17:16:26 | INFO | "./app\services\material.py:245": download_videos - video saved: .\storage\cache_videos/vid-519fe364b1907dd88ab58338962e78e0.mp4
2024-11-21 17:16:26 | INFO | "./app\services\material.py:240": download_videos - downloading video: https://cdn.pixabay.com/video/2016/05/04/3013-165457883_large.mp4
2024-11-21 17:16:27 | INFO | "./app\services\material.py:245": download_videos - video saved: .\storage\cache_videos/vid-70a9abba4467d00b66a07cacc9d2b9e9.mp4
2024-11-21 17:16:27 | INFO | "./app\services\material.py:250": download_videos - total duration of downloaded videos: 51.0 seconds, skip downloading more
2024-11-21 17:16:27 | SUCCESS | "./app\services\material.py:256": download_videos - downloaded 17 videos
2024-11-21 17:16:27 | INFO | "./app\services\task.py:175": generate_final_videos -

## combining video: 1 => .\storage\tasks\17e3810f-031e-4a7b-aa7e-134dd5bec899\combined-1.mp4
2024-11-21 17:16:27 | INFO | "./app\services\video.py:43": combine_videos - max duration of audio: 49.51 seconds
2024-11-21 17:16:27 | INFO | "./app\services\video.py:47": combine_videos - each clip will be maximum 3 seconds long
2024-11-21 17:16:27.739 Uncaught app exception
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\giova\MoneyPrinterTurbo\webui\Main.py", line 787, in <module>
    result = tm.start(task_id=task_id, params=params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\giova\MoneyPrinterTurbo\app\services\task.py", line 299, in start
    final_video_paths, combined_video_paths = generate_final_videos(
                                              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\giova\MoneyPrinterTurbo\app\services\task.py", line 176, in generate_final_videos
    video.combine_videos(
  File "C:\Users\giova\MoneyPrinterTurbo\app\services\video.py", line 64, in combine_videos
    split_clip = clip.subclip(start_time, end_time)
                 ^^^^^^^^^^^^
AttributeError: 'VideoFileClip' object has no attribute 'subclip'

**Comment by TarikKalyoncu** [comment]
I also got this error "AttributeError: 'VideoFileClip' object has no attribute 'subclip'"

I solved it by doing this

pip uninstall moviepy
pip install moviepy==2.0.0.dev2

**Comment by smolderiukas** [comment]
Same, not working,  even with better requirements and manual install: 
pip uninstall moviepy
pip install moviepy==2.0.0.dev2

**Comment by jim-qiu** [comment]
> pip install moviepy==2.0.0.dev2
pip uninstall moviepy
pip install moviepy==1.0.3
![image](https://github.com/user-attachments/assets/437d1adc-7d43-4d5c-a5cf-208b466ae411)

**Comment by yyhhyyyyyy** [comment]
Please pull the latest code to access the fix.

**Comment by smolderiukas** [comment]
Still doesn't work with conda, new code or new requirements. 
AttributeError: 'VideoFileClip' object has no attribute 'subclipped'
Traceback:
File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
File "/MoneyPrinterTurbo/webui/Main.py", line 787, in <module>
    result = tm.start(task_id=task_id, params=params)
File "/MoneyPrinterTurbo/app/services/task.py", line 299, in start
    final_video_paths, combined_video_paths = generate_final_videos(
File "/MoneyPrinterTurbo/app/services/task.py", line 176, in generate_final_videos
    video.combine_videos(
File "/MoneyPrinterTurbo/app/services/video.py", line 64, in combine_videos
    split_clip = clip.subclipped(start_time, end_time)

**Comment by kiankyars** [comment]
> ==2.0.0.dev2

Thank you so much Tarik, this worked for me, so satisfying after >1 hour of debugging and HOLY CRAP MOVIEPY IS A PAIN TO DEAL WITH.

I am using uv, and here are my python versions in case anyone wants something that will work

# numpy==2.0.2
opencv-python==4.10.0.84
python-dotenv==1.0.1certifi==2024.12.14
charset-normalizer==3.4.1
decorator==4.4.2
idna==3.10
imageio==2.37.0
imageio-ffmpeg==0.6.0
moviepy==2.0.0.dev2
numpy==2.2.2
opencv-python==4.10.0.84
pillow==11.1.0
proglog==0.1.10
python-dotenv==1.0.1
requests==2.32.3
tqdm==4.67.1
urllib3==2.3.0

Furthermore, use 

from moviepy.audio.io.AudioFileClip import AudioFileClip
from moviepy.video.io.VideoFileClip import VideoFileClip

if
  from moviepy.editor import VideoFileClip, AudioFileClip 
does not work.

have a nice day!
