### ISSUE TITLE
视频合成最后一步出错错误

### ISSUE THREAD

**Issue by clank7378** [harry0703/MoneyPrinterTurbo#538]
2024-12-02 21:49:54.589 Uncaught app exception
Traceback (most recent call last):
  File "E:\money\lib\python\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
  File "E:\money\MoneyPrinterTurbo\webui\Main.py", line 787, in <module>
    result = tm.start(task_id=task_id, params=params)
  File "E:\money\MoneyPrinterTurbo\app\services\task.py", line 299, in start
    final_video_paths, combined_video_paths = generate_final_videos(
  File "E:\money\MoneyPrinterTurbo\app\services\task.py", line 192, in generate_final_videos
    video.generate_video(
  File "E:\money\MoneyPrinterTurbo\app\services\video.py", line 280, in generate_video
    bgm_file = get_bgm_file(bgm_type=params.bgm_type, bgm_file=params.bgm_file)
  File "E:\money\MoneyPrinterTurbo\app\services\video.py", line 26, in get_bgm_file
    return random.choice(files)
  File "E:\money\lib\python\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

**Comment by harry0703** [comment]
Fixed on the current main branch.

The crash here came from `get_bgm_file()` calling `random.choice()` on an empty background-music list when `bgm_type=random` and the song directory had no `mp3` files. The current main branch now falls back to “no BGM” in that case instead of raising `IndexError`.

I also validated the fix locally against an empty song directory before closing this.
