### ISSUE TITLE
NameError: name 'AudioFileClip' is not defined

### ISSUE THREAD

**Issue by CodeVeteran** [harry0703/MoneyPrinterTurbo#544]
config:
{
    "video_subject": "不要等待机会，而是创造机会",
    "video_script": "",
    "video_terms": "",
    "video_aspect": "9:16",
    "video_concat_mode": "random",
    "video_clip_duration": 3,
    "video_count": 1,
    "video_source": "pexels",
    "video_materials": null,
    "video_language": "",
    "voice_name": "de-DE-FlorianMultilingualNeural-Male",
    "voice_volume": 1.0,
    "voice_rate": 1.0,
    "bgm_type": "random",
    "bgm_file": "",
    "bgm_volume": 0.2,
    "subtitle_enabled": true,
    "subtitle_position": "bottom",
    "custom_position": 70.0,
    "font_name": "MicrosoftYaHeiBold.ttc",
    "text_fore_color": "#FFFFFF",
    "text_background_color": true,
    "font_size": 60,
    "stroke_color": "#000000",
    "stroke_width": 1.5,
    "n_threads": 2,
    "paragraph_number": 1
}
error log:
2024-12-05 12:05:55 | SUCCESS | "./app\services\material.py:256": download_videos - downloaded 11 videos
2024-12-05 12:05:55 | INFO | "./app\services\task.py:175": generate_final_videos -

## combining video: 1 => .\storage\tasks\f3e256a7-bf2f-4254-9224-38b95420a83b\combined-1.mp4
2024-12-05 12:05:55.121 Uncaught app exception
Traceback (most recent call last):
  File "d:\Users\admin\anaconda3\envs\MoneyPrinterTurbo\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
  File "E:\gitwork\MoneyPrinterTurbo\webui\Main.py", line 787, in <module>
    result = tm.start(task_id=task_id, params=params)
  File "E:\gitwork\MoneyPrinterTurbo\app\services\task.py", line 299, in start
    final_video_paths, combined_video_paths = generate_final_videos(
  File "E:\gitwork\MoneyPrinterTurbo\app\services\task.py", line 176, in generate_final_videos
    video.combine_videos(
  File "E:\gitwork\MoneyPrinterTurbo\app\services\video.py", line 41, in combine_videos
    audio_clip = AudioFileClip(audio_file)
NameError: name 'AudioFileClip' is not defined
![image](https://github.com/user-attachments/assets/4819a09c-9d69-4f63-a0f7-fc28a9b999b4)

**Comment by CodeVeteran** [comment]
## generating audio
2024-12-05 12:03:53 | INFO | "./app\services\voice.py:1081": azure_tts_v1 - start, voice name: de-DE-FlorianMultilingualNeural, try: 1
2024-12-05 12:04:04 | INFO | "./app\services\voice.py:1101": azure_tts_v1 - completed, output file: .\storage\tasks\f3e256a7-bf2f-4254-9224-38b95420a83b\audio.mp3
2024-12-05 12:04:04 | INFO | "./app\services\task.py:103": generate_subtitle -

## generating subtitle, provider: edge
2024-12-05 12:04:04 | ERROR | "./app\services\voice.py:1290": create_subtitle - failed, error: file_to_subtitles() got an unexpected keyword argument 'encoding'
2024-12-05 12:04:04 | WARNING | "./app\services\task.py:112": generate_subtitle - subtitle file not found, fallback to whisper
2024-12-05 12:04:04 | INFO | "./app\services\subtitle.py:26": create - loading model: large-v3, device: CPU, compute_type: int8
An error occured while synchronizing the model Systran/faster-whisper-large-v3 from the Hugging Face Hub:
An error happened while trying to locate the files on the Hub and we cannot find the appropriate snapshot folder for the specified revision on the local disk. Please check your internet connection and try again.
Trying to load the model directly from the local cache, if it exists.
2024-12-05 12:04:25 | ERROR | "./app\services\subtitle.py:34": create - failed to load model: Cannot find an appropriate cached snapshot folder for the specified revision on the local disk and outgoing traffic has been disabled. To enable repo look-ups and downloads online, pass 'local_files_only=False' as input.

********************************************
this may be caused by network issue.
please download the model manually and put it in the 'models' folder.
see [README.md FAQ](https://github.com/harry0703/MoneyPrinterTurbo) for more details.
********************************************


2024-12-05 12:04:25 | INFO | "./app\services\task.py:116": generate_subtitle -

**Comment by yyhhyyyyyy** [comment]
Please pull the latest code, create a new conda environment, and then run 
```
conda create -n MoneyPrinterTurbo python=3.11
conda activate MoneyPrinterTurbo
pip install -r requirements.txt
```
