### ISSUE TITLE
OSError: [WinError 6] 句柄无效。

### ISSUE THREAD

**Issue by qqqxc** [harry0703/MoneyPrinterTurbo#545]
在生成视频的最后一步报错了，报错信息如下
Exception ignored in: <function FFMPEG_VideoReader.__del__ at 0x000002B23DBF6680>
Traceback (most recent call last):
  File "D:\anaconda\envs\MoneyPrinterTurbo\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 199, in __del__
    self.close()
  File "D:\anaconda\envs\MoneyPrinterTurbo\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 190, in close
    self.proc.terminate()
  File "D:\anaconda\envs\MoneyPrinterTurbo\lib\subprocess.py", line 1589, in terminate
    _winapi.TerminateProcess(self._handle, 1)
OSError: [WinError 6] 句柄无效。
从我的浏览器中返回的信息如下，我想请问这是遇到了什么问题，我需要重新装一个ffmpeg的库吗
File "D:\anaconda\envs\MoneyPrinterTurbo\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
File "D:\badminton_get\try_video\MoneyPrinterTurbo\webui\Main.py", line 788, in <module>
    result = tm.start(task_id=task_id, params=params)
File "D:\badminton_get\try_video\MoneyPrinterTurbo\app\services\task.py", line 299, in start
    final_video_paths, combined_video_paths = generate_final_videos(
File "D:\badminton_get\try_video\MoneyPrinterTurbo\app\services\task.py", line 192, in generate_final_videos
    video.generate_video(
File "D:\badminton_get\try_video\MoneyPrinterTurbo\app\services\video.py", line 276, in generate_video
    sub = SubtitlesClip(subtitles=subtitle_path, encoding="utf-8")

**Comment by yyhhyyyyyy** [comment]
Which version are you using?
If it's the latest version, have you recreated a virtual environment and reinstalled the dependencies?

**Comment by StevenSunzh** [comment]
我也报这个错。V1.2.2版本
运行情况是：生成一个170秒的视频，在视频合并时报如下错误
`2025-02-11 09:26:02 | INFO | "./app\services\video.py:141": combine_videos - Using transition mode: Shuffle
Exception ignored in: <function FFMPEG_VideoReader.__del__ at 0x0000000035B38310>
Traceback (most recent call last):
  File "E:\Projects\AI\zsp\tools\MoneyPrinterTurbo_all\lib\python\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 257, in __del__
    self.close()
  File "E:\Projects\AI\zsp\tools\MoneyPrinterTurbo_all\lib\python\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 247, in close
    if self.proc.poll() is None:
  File "E:\Projects\AI\zsp\tools\MoneyPrinterTurbo_all\lib\python\lib\subprocess.py", line 1181, in poll
    return self._internal_poll()
  File "E:\Projects\AI\zsp\tools\MoneyPrinterTurbo_all\lib\python\lib\subprocess.py", line 1493, in _internal_poll
    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
OSError: [WinError 6] 句柄无效。
Exception ignored in: <function FFMPEG_VideoReader.__del__ at 0x0000000035B38310>
Traceback (most recent call last):
  File "E:\Projects\AI\zsp\tools\MoneyPrinterTurbo_all\lib\python\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 257, in __del__
    self.close()
  File "E:\Projects\AI\zsp\tools\MoneyPrinterTurbo_all\lib\python\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 247, in close
    if self.proc.poll() is None:
  File "E:\Projects\AI\zsp\tools\MoneyPrinterTurbo_all\lib\python\lib\subprocess.py", line 1181, in poll
    return self._internal_poll()
  File "E:\Projects\AI\zsp\tools\MoneyPrinterTurbo_all\lib\python\lib\subprocess.py", line 1493, in _internal_poll
    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
OSError: [WinError 6] 句柄无效。
Exception ignored in: <function FFMPEG_VideoReader.__del__ at 0x0000000035B38310>
Traceback (most recent call last):
  File "E:\Projects\AI\zsp\tools\MoneyPrinterTurbo_all\lib\python\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 257, in __del__
    self.close()
  File "E:\Projects\AI\zsp\tools\MoneyPrinterTurbo_all\lib\python\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 247, in close
    if self.proc.poll() is None:
  File "E:\Projects\AI\zsp\tools\MoneyPrinterTurbo_all\lib\python\lib\subprocess.py", line 1181, in poll
    return self._internal_poll()
  File "E:\Projects\AI\zsp\tools\MoneyPrinterTurbo_all\lib\python\lib\subprocess.py", line 1493, in _internal_poll
    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
OSError: [WinError 6] 句柄无效。
Exception ignored in: <function FFMPEG_VideoReader.__del__ at 0x0000000035B38310>
Traceback (most recent call last):
  File "E:\Projects\AI\zsp\tools\MoneyPrinterTurbo_all\lib\python\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 257, in __del__
    self.close()
  File "E:\Projects\AI\zsp\tools\MoneyPrinterTurbo_all\lib\python\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 247, in close
    if self.proc.poll() is None:
  File "E:\Projects\AI\zsp\tools\MoneyPrinterTurbo_all\lib\python\lib\subprocess.py", line 1181, in poll
    return self._internal_poll()
  File "E:\Projects\AI\zsp\tools\MoneyPrinterTurbo_all\lib\python\lib\subprocess.py", line 1493, in _internal_poll
    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
OSError: [WinError 6] 句柄无效。
Exception ignored in: <function FFMPEG_VideoReader.__del__ at 0x0000000035B38310>
Traceback (most recent call last):
  File "E:\Projects\AI\zsp\tools\MoneyPrinterTurbo_all\lib\python\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 257, in __del__
    self.close()
  File "E:\Projects\AI\zsp\tools\MoneyPrinterTurbo_all\lib\python\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 247, in close
    if self.proc.poll() is None:
  File "E:\Projects\AI\zsp\tools\MoneyPrinterTurbo_all\lib\python\lib\subprocess.py", line 1181, in poll
    return self._internal_poll()
  File "E:\Projects\AI\zsp\tools\MoneyPrinterTurbo_all\lib\python\lib\subprocess.py", line 1493, in _internal_poll
    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
OSError: [WinError 6] 句柄无效。
`

**Comment by harry0703** [comment]
This report belongs to the older MoviePy-based merge/finalize path. Since then, the main branch has substantially changed the video pipeline: clip cleanup is more explicit, reader/mask resources are closed more aggressively, and the combine path no longer relies on the same progressive MoviePy merge flow that originally triggered many of these handle/reader teardown errors.

I’m closing this as fixed by the current main branch.
