### ISSUE TITLE
生成视频时报错

### ISSUE THREAD

**Issue by xinjiangyin** [harry0703/MoneyPrinterTurbo#67]
报错内容如下：
   tm.start(task_id=task_id, params=cfg)
  File "/home/MoneyPrinterTurbo-main/app/services/task.py", line 133, in start
    video.combine_videos(combined_video_path=combined_video_path,
  File "/home/MoneyPrinterTurbo-main/app/services/video.py", line 84, in combine_videos
    clip = clip.resize((video_width, video_height))
  File "/usr/local/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/video/fx/resize.py", line 165, in resize
    newclip = clip.fl_image(fl)
  File "/usr/local/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/video/VideoClip.py", line 576, in fl_image
    return self.fl(lambda gf, t: image_func(gf(t)), apply_to)
  File "/usr/local/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/Clip.py", line 141, in fl
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "<decorator-gen-68>", line 2, in set_make_frame
  File "/usr/local/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/decorators.py", line 15, in outplace
    f(newclip, *a, **k)
  File "/usr/local/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/video/VideoClip.py", line 740, in set_make_frame
    self.size = self.get_frame(0).shape[:2][::-1]
  File "<decorator-gen-11>", line 2, in get_frame
  File "/usr/local/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "/usr/local/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/Clip.py", line 98, in get_frame
    return self.make_frame(t)
  File "/usr/local/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/Clip.py", line 141, in <lambda>
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "/usr/local/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/video/VideoClip.py", line 576, in <lambda>
    return self.fl(lambda gf, t: image_func(gf(t)), apply_to)
  File "/usr/local/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/video/fx/resize.py", line 163, in fl
    return resizer(pic.astype("uint8"), newsize)
  File "/usr/local/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/video/fx/resize.py", line 37, in resizer
    resized_pil = pilim.resize(newsize[::-1], Image.ANTIALIAS)
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

解决方法：
删除Pillow 库，重新安装9.0.0版本后，不再报错

**Comment by xinjiangyin** [comment]
Pillow 库重新安装后，还是不行，后来还是出现此错误了

**Comment by qiqi258** [comment]
我更新到了   Pillow 库已经是最新版本 10.2.0 了  暂时没问题

**Comment by xinjiangyin** [comment]
> 我更新到了 Pillow 库已经是最新版本 10.2.0 了 暂时没问题

谢谢，我一开始也是用的10.2.0版本，会报这个错，但这个报错不是每次都出现，有时可以正常生成视频，有时会报错。

**Comment by harry0703** [comment]
requirements 文件里面是 pillow~=10.2.0 的版本，9.x 和 10.x 有些API接口不一样，需要用10.x的版本

可以把10.x的完整报错信息发出来看看么？谢谢

**Comment by xinjiangyin** [comment]
> requirements 文件里面是 pillow~=10.2.0 的版本，9.x 和 10.x 有些API接口不一样，需要用10.x的版本
> 
> 可以把10.x的完整报错信息发出来看看么？谢谢

完整报错信息如下：

2024-03-26 12:17:37 | INFO | "./app/services/material.py:129": download_videos - total duration of downloaded videos: 21.0 seconds, skip downloading more
2024-03-26 12:17:37 | SUCCESS | "./app/services/material.py:133": download_videos - downloaded 7 videos
2024-03-26 12:17:37 | INFO | "./app/services/task.py:132": start -

## combining video: 1 => ./storage/tasks/cb7ee7f6-0c3e-430c-8957-8959d2681750/combined-1.mp4
2024-03-26 12:17:37 | INFO | "./app/services/video.py:39": combine_videos - max duration of audio: 18.46 seconds
2024-03-26 12:17:37 | INFO | "./app/services/video.py:43": combine_videos - each clip will be maximum 3 seconds long
2024-03-26 12:17:38 | INFO | "./app/services/video.py:83": combine_videos - resizing video to 1080 x 1920
2024-03-26 12:17:39.429 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
  File "/home/MoneyPrinterTurbo-main/webui/Main.py", line 247, in <module>
    tm.start(task_id=task_id, params=cfg)
  File "/home/MoneyPrinterTurbo-main/app/services/task.py", line 133, in start
    video.combine_videos(combined_video_path=combined_video_path,
  File "/home/MoneyPrinterTurbo-main/app/services/video.py", line 84, in combine_videos
    clip = clip.resize((video_width, video_height))
  File "/usr/local/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/video/fx/resize.py", line 165, in resize
    newclip = clip.fl_image(fl)
  File "/usr/local/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/video/VideoClip.py", line 576, in fl_image
    return self.fl(lambda gf, t: image_func(gf(t)), apply_to)
  File "/usr/local/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/Clip.py", line 141, in fl
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "<decorator-gen-68>", line 2, in set_make_frame
  File "/usr/local/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/decorators.py", line 15, in outplace
    f(newclip, *a, **k)
  File "/usr/local/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/video/VideoClip.py", line 740, in set_make_frame
    self.size = self.get_frame(0).shape[:2][::-1]
  File "<decorator-gen-11>", line 2, in get_frame
  File "/usr/local/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "/usr/local/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/Clip.py", line 98, in get_frame
    return self.make_frame(t)
  File "/usr/local/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/Clip.py", line 141, in <lambda>
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "/usr/local/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/video/VideoClip.py", line 576, in <lambda>
    return self.fl(lambda gf, t: image_func(gf(t)), apply_to)
  File "/usr/local/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/video/fx/resize.py", line 163, in fl
    return resizer(pic.astype("uint8"), newsize)
  File "/usr/local/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/moviepy/video/fx/resize.py", line 37, in resizer
    resized_pil = pilim.resize(newsize[::-1], Image.ANTIALIAS)
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

**Comment by harry0703** [comment]
谢谢，看看如何定位和优化一下

**Comment by smaltum** [comment]
@xinjiangyin  将pillow~=8.4.0,moviepy~=1.0.3 在centos上测试可行

**Comment by edusanttini** [comment]
Im facing this same issue non stop

**Comment by smaltum** [comment]
> Im facing this same issue non stop
try to set the pillow version in requirements.txt like this:
`
pillow~=8.4.0,moviepy~=1.0.3
`

**Comment by AemonChan** [comment]
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
我用的pillow9.5生成第2个就出错了

**Comment by smaltum** [comment]
@AemonChan 改8.4.0试试
