### ISSUE TITLE
使用第三方openai的key404报错

### ISSUE THREAD

**Issue by SarcomTDG** [harry0703/MoneyPrinterTurbo#72]
使用第三方的openai的key情况下，更改host和key，报错404 报错代码2024-03-27 15:11:22 | INFO | "./app\services\llm.py:15": _generate_response - llm provider: openai
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\Anacond3\envs\MoneyPrinterTurbo\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 412, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\Anacond3\envs\MoneyPrinterTurbo\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "D:\Anacond3\envs\MoneyPrinterTurbo\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\Anacond3\envs\MoneyPrinterTurbo\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Anacond3\envs\MoneyPrinterTurbo\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "D:\Anacond3\envs\MoneyPrinterTurbo\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "D:\Anacond3\envs\MoneyPrinterTurbo\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\Anacond3\envs\MoneyPrinterTurbo\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "D:\Anacond3\envs\MoneyPrinterTurbo\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "D:\Anacond3\envs\MoneyPrinterTurbo\lib\site-packages\starlette\routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Anacond3\envs\MoneyPrinterTurbo\lib\site-packages\starlette\routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "D:\Anacond3\envs\MoneyPrinterTurbo\lib\site-packages\starlette\routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "D:\Anacond3\envs\MoneyPrinterTurbo\lib\site-packages\starlette\routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\Anacond3\envs\MoneyPrinterTurbo\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "D:\Anacond3\envs\MoneyPrinterTurbo\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "D:\Anacond3\envs\MoneyPrinterTurbo\lib\site-packages\starlette\routing.py", line 74, in app
    response = await func(request)
  File "D:\Anacond3\envs\MoneyPrinterTurbo\lib\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "D:\Anacond3\envs\MoneyPrinterTurbo\lib\site-packages\fastapi\routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "D:\Anacond3\envs\MoneyPrinterTurbo\lib\site-packages\starlette\concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "D:\Anacond3\envs\MoneyPrinterTurbo\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\Anacond3\envs\MoneyPrinterTurbo\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "D:\Anacond3\envs\MoneyPrinterTurbo\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "D:\code\python\MoneyPrinterTurbo-main\app\controllers\v1\video.py", line 29, in create_video
    result = tm.start(task_id=task_id, params=body)
  File "D:\code\python\MoneyPrinterTurbo-main\app\services\task.py", line 51, in start
    video_script = llm.generate_script(video_subject=video_subject, language=params.video_language,
  File "D:\code\python\MoneyPrinterTurbo-main\app\services\llm.py", line 105, in generate_script
    response = _generate_response(prompt=prompt)
  File "D:\code\python\MoneyPrinterTurbo-main\app\services\llm.py", line 68, in _generate_response
    response = client.chat.completions.create(
  File "D:\Anacond3\envs\MoneyPrinterTurbo\lib\site-packages\openai\_utils\_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
  File "D:\Anacond3\envs\MoneyPrinterTurbo\lib\site-packages\openai\resources\chat\completions.py", line 667, in create
    return self._post(
  File "D:\Anacond3\envs\MoneyPrinterTurbo\lib\site-packages\openai\_base_client.py", line 1208, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "D:\Anacond3\envs\MoneyPrinterTurbo\lib\site-packages\openai\_base_client.py", line 897, in request
    return self._request(
  File "D:\Anacond3\envs\MoneyPrinterTurbo\lib\site-packages\openai\_base_client.py", line 988, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>

**Comment by smaltum** [comment]
@SarcomTDG 配置不对吧,参考配置：
    openai_api_key = "your_key"
    openai_base_url = "http://openai-api.aoscdn.com/v1/"
    openai_model_name = "gpt-4-turbo-preview"

**Comment by smaltum** [comment]
@SarcomTDG 
配置不对吧，参考配置：
```
    openai_api_key = "your_key"
    openai_base_url = "you_proxy"
    openai_model_name = "gpt-4-turbo-preview"
```

**Comment by SarcomTDG** [comment]
> @SarcomTDG 配置不对吧，参考配置：
> 
> ```
>     openai_api_key = "your_key"
>     openai_base_url = "you_proxy"
>     openai_model_name = "gpt-4-turbo-preview"
> ```
配置了 
![Uploading 微信截图_20240327152513.png…]()

**Comment by SarcomTDG** [comment]
> @SarcomTDG 配置不对吧，参考配置：
> 
> ```
>     openai_api_key = "your_key"
>     openai_base_url = "you_proxy"
>     openai_model_name = "gpt-4-turbo-preview"
> ```

相关配置了，我使用的完全兼容OpenAI API格式
![微信截图_20240327152513](https://github.com/harry0703/MoneyPrinterTurbo/assets/95288331/9b2214b0-e6e8-4544-a34d-cd37f3e84824)

**Comment by smaltum** [comment]
@SarcomTDG  
直接curl下你的代理地址试试通不通

**Comment by SarcomTDG** [comment]
> @SarcomTDG 直接curl下你的代理地址试试通不通

解决了 代理地址需要携带/V1参数才可以
![Bfi12r9h_400x400](https://github.com/harry0703/MoneyPrinterTurbo/assets/95288331/30cd4833-c64d-4c8a-9823-4fe8ed47b1a3)
