### ISSUE TITLE
utf-8 codec can‘t decode bytes请问这个报错是因为什么，好像是概率性的

### ISSUE THREAD

**Issue by zhuangzhuang3** [harry0703/MoneyPrinterTurbo#96]

**Comment by zhuangzhuang3** [comment]
"./app/services/lLm.py:14":_generate response - Ulm provider: g4f
2024-03-28 17:09:23.863 Uncaught app exception
Traceback (most recent call last):
1dhuos unuÃ un ‘ZtS awl (./druauunu 1d/uos/Jauunuqduos/awqunu/4)1Weauqs/sabexped-a1)s/OT Suoy1/d/q!1/oqun]Ja1MudKauoW/sAu3/Sepu001uw/Ado/, a1日
exec(code, module. dict  )
File "/home/project/MoneyPrinterTurbo/webui/Main.py", line 117, in <module>
script = llm.generate script(video subject=cfg.video_subject, language=cfg.video_language)
File "/home/project/MoneyPrinterTurbo/app/services/llm.py", line 118, in generate script
response = generate response(prompt=prompt)
File "/home/project/MoneyPrinterTurbo/app/services/llm.py", line 20, in _generate_response
content = g4f.ChatCompletion.create(
File "/opt/miniconda3/envs/MoneyPrinterTurbo/Lib/python3.10/site-packages/g4f/__init_.py", line 149, in create
return result if stream else '.join([str(chunk) for chunk in result])
File "/opt/miniconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/g4f/  init_.py", Line 149, in <listcomp>
return result if stream else '.join([str(chunk) for chunk in result])
File "/opt/miniconda3/envs/MoneyPrinterTurbo/Lib/python3.10/site-packages/g4f/providers/retry_provider.py", line 79, in create_completion
raise e
File "/opt/miniconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/g4f/providers/retry provider.py", line 69, in create_completion
for token in provider.create completion(model, messages, stream, **kwargs):
File "/opt/miniconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/g4f/providers/base_provider.py", line 206, in create_completion
yield loop.run_until_complete(await_callback(gen. anext__))
File "/opt/miniconda3/envs/MoneyPrinterTurbo/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
return future.result()
File "/opt/miniconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/g4f/providers/base_provider.py", line 202, in await_callback
return await callback( )
File "/opt/miniconda3/envs/MoneyPrinterTurbo/lib/python3.10/site-packages/g4f/Provider/FreeGpt.py", line 48, in create async_generator
munun	( ) annhan мunun -
InicodeDecodeError: 'utf-8' codec can't decode bytes in position 126-127: unexpected end of data

**Comment by harry0703** [comment]
这个是 g4f 依赖库抛出来的异常，**大概率** 是因为openai没有返回正确的回复
**g4f的freegpt，不太稳定**
建议可以使用openai的，或者国内的模型，比如 moonshot

**Comment by zhuangzhuang3** [comment]
> 这个是 g4f 依赖库抛出来的异常，**大概率** 是因为openai没有返回正确的回复 **g4f的freegpt，不太稳定** 建议可以使用openai的，或者国内的模型，比如 moonshot

好的，感谢作者大大
